/* ===== bank expansion (appended so earlier question ids stay stable) ===== */
P1B.push(
["남자가 차 트렁크에 여행 가방을 싣고 있다",["He's loading a suitcase into a car.","He's opening a car door.","He's fixing a tire.","He's washing a car."],0,"load A into B = A를 B에 싣다."],
["여자가 컴퓨터 화면을 보며 키보드로 타이핑하고 있다",["She's unplugging a monitor.","She's typing on a keyboard.","She's cleaning a screen.","She's hanging up a phone."],1,"사진 속 동작 그대로. 화면을 닦거나 전원을 뽑는 동작은 없음."],
["도서관 서가에 책들이 빽빽이 꽂혀 있다 (사람 없음)",["A librarian is sorting books.","Books are being packed into boxes.","Shelves are filled with books.","Some books are scattered on the floor."],2,"filled with = ~로 가득 찬(상태)."],
["두 사람이 악수를 하고 있고 한 사람은 서류 가방을 들고 있다",["They're shaking hands.","They're exchanging business cards.","They're opening a briefcase.","They're sitting at a table."],0,"shake hands = 악수하다."],
["남자가 잔디 깎는 기계를 밀고 있다",["He's planting some flowers.","He's mowing the lawn.","He's raking leaves.","He's watering the grass."],1,"mow the lawn = 잔디를 깎다."],
["우산 여러 개가 가게 입구 옆 통에 꽂혀 있다 (사람 없음)",["Umbrellas have been placed in a stand.","A woman is opening an umbrella.","It's raining heavily.","Umbrellas are being sold on the street."],0,"have been placed = 놓여 있는 상태."],
["여자가 계단 난간을 잡고 계단을 올라가고 있다",["She's going down an escalator.","She's holding onto a railing.","She's sitting on the stairs.","She's carrying a ladder."],1,"hold onto a railing = 난간을 잡다."],
["작업자가 벽에 페인트를 칠하고 있다",["A worker is painting a wall.","A worker is removing a window.","A wall is being torn down.","Some paint cans are being delivered."],0,"사진 속 사람의 동작."],
["카페 테라스에 파라솔이 펼쳐져 있고 테이블이 비어 있다",["People are dining outside.","Some umbrellas are shading the tables.","A waiter is cleaning a table.","Chairs are being stacked."],1,"shade = 그늘을 드리우다. 사람 없는 사진."],
["남자가 선반에서 상자를 내리고 있다",["He's taking a box off a shelf.","He's writing on a box.","He's opening a cabinet.","He's sweeping the floor."],0,"take A off B = B에서 A를 내리다."],
["사람들이 버스에 줄지어 타고 있다",["People are getting off a train.","People are boarding a bus.","A bus is being repaired.","People are waiting at a crosswalk."],1,"board = 탑승하다."],
["노트북, 커피잔, 공책이 책상 위에 놓여 있다 (사람 없음)",["A laptop is being turned on.","Some items are on a desk.","A man is drinking coffee.","A notebook is being written in."],1,"사람이 없으니 사람 동작·진행 수동은 오답."],
["여자가 복도에서 카트를 밀고 있다",["She's pushing a cart down a hallway.","She's opening a door.","She's parking a car.","She's mopping the floor."],0,"push a cart = 카트를 밀다."],
["남자 둘이 테이블을 함께 들어 옮기고 있다",["They're setting a table.","They're lifting a table.","They're sitting at a table.","They're painting a table."],1,"lift = 들어 올리다."],
["건물 앞에 자전거 여러 대가 거치대에 세워져 있다 (사람 없음)",["Bicycles are lined up in a rack.","Cyclists are racing on a road.","A bicycle is being repaired.","A man is locking his bike."],0,"lined up = 줄지어 있는(상태)."],
["여자가 마이크 앞에서 연설하고 있다",["She's adjusting a camera.","She's speaking into a microphone.","She's taking notes.","She's leaving the stage."],1,"speak into a microphone."],
["남자가 무릎을 꿇고 바닥 타일을 붙이고 있다",["He's kneeling on the floor.","He's lying on a sofa.","He's climbing a ladder.","He's carrying some carpet."],0,"kneel = 무릎 꿇다. 자세를 묘사하는 정답도 자주 나옵니다."],
["여러 사람이 회의실 테이블에 둘러앉아 있다",["People are seated around a table.","People are leaving a room.","A table is being moved.","Chairs are stacked in a corner."],0,"be seated = 앉아 있다."],
["배 한 척이 다리 아래를 지나가고 있다",["A boat is passing under a bridge.","A bridge is being built.","Passengers are getting off a boat.","A boat is tied to a dock."],0,"pass under = 아래를 지나가다."],
["여자가 가게 진열대에서 옷을 살펴보고 있다",["She's trying on a hat.","She's examining some clothing.","She's paying at a register.","She's folding towels."],1,"examine = 살펴보다. clothing = 옷."]);

P2N.push(
["Where's the budget meeting being held?",["In Conference Room C.","About the new budget.","It was held last week."],0,"Where → 장소.","의문사"],
["When did you move to this department?",["About three months ago.","To the sales department.","It moved quickly."],0,"When → 시점.","의문사"],
["Who approved the vacation request?",["For two weeks.","The department head did.","Yes, it was approved."],1,"Who → 사람. 의문사 질문에 Yes는 오답.","의문사"],
["Why is the elevator out of service?",["It's being inspected today.","On the tenth floor.","Take the stairs next time."],0,"Why → 이유.","의문사"],
["How many people are coming to the workshop?",["Around thirty so far.","In the main hall.","It's coming soon."],0,"How many → 수량.","의문사"],
["Which route is faster to the airport?",["The highway, definitely.","The flight leaves at noon.","Faster than I expected."],0,"Which → 선택지 중 하나.","의문사"],
["What's the password for the Wi-Fi?",["It's posted on the wall by the door.","The word is spelled wrong.","Yes, it's fast."],0,"직접 말하지 않고 위치를 알려 주는 간접 응답.","간접"],
["How do I get to the parking garage?",["Take the elevator down to level B1.","It costs ten dollars.","I parked there yesterday."],0,"How → 방법.","의문사"],
["When will the renovations be finished?",["The contractor hasn't said yet.","In the lobby.","They finished the report."],0,"‘아직 말 안 했다’ 간접 응답. finish 반복 함정.","간접"],
["Who's giving the keynote speech?",["Let me check the program.","It was a great speech.","At nine o'clock."],0,"‘프로그램을 확인해 볼게요’ 간접 응답.","간접"],
["Where should I put these boxes?",["Anywhere near the door is fine.","Twelve boxes.","They're very heavy."],0,"Where → 위치(아무 데나).","의문사"],
["Why didn't Ms. Park come to the meeting?",["She had a doctor's appointment.","The meeting room is booked.","She'll come by bus."],0,"Why → 이유.","의문사"],
["Did you receive my e-mail about the schedule?",["Yes, I'll reply this afternoon.","The schedule is on the wall.","I sent a letter."],0,"Yes + 부연.","일반·부정"],
["Is this seat taken?",["No, go ahead.","I'll take the bus.","It's a comfortable seat."],0,"비어 있다 = No, 앉으세요.","일반·부정"],
["Doesn't the train leave at six?",["It was delayed by twenty minutes.","I'll train them tomorrow.","Six tickets, please."],0,"지연됐다는 간접 응답. train 다의어 함정.","일반·부정"],
["Are you going to apply for the manager position?",["I'm still thinking about it.","The application was long.","He's a good manager."],0,"‘아직 생각 중’ 간접 응답.","일반·부정"],
["Has the client signed the contract yet?",["She's reviewing it with her lawyer.","Sign here, please.","A two-year contract."],0,"아직 아님을 간접적으로.","일반·부정"],
["Can you work this Saturday?",["I have family plans, unfortunately.","It works well.","On Saturday afternoon."],0,"거절 + 이유.","요청·제안"],
["Should we take a taxi or walk to the restaurant?",["It's only five minutes away.","The taxi driver was kind.","I should."],0,"‘5분 거리’ → 걷자는 간접 선택.","선택"],
["Do you prefer the blue design or the green one?",["I like them both.","Yes, I prefer it.","The designer is here."],0,"둘 다 좋다.","선택"],
["Will you pay by cash or card?",["Card, please.","It's in my wallet.","Yes, I will."],0,"하나 선택.","선택"],
["Is the report due Monday or Tuesday?",["The manager wants it by Friday.","It's a long report.","Yes, it is."],0,"둘 다 아닌 제3의 응답.","선택"],
["You're the new sales manager, aren't you?",["Yes, I started last week.","The sales went up.","He manages well."],0,"사실 확인 → Yes + 부연.","부가"],
["The copier is working again, isn't it?",["A technician fixed it this morning.","Make ten copies.","It's working hours."],0,"고쳐졌다 = 그렇다.","부가"],
["We're meeting the client at two, right?",["Actually, it's been moved to three.","The client is happy.","Two copies, please."],0,"Actually로 정정하는 응답.","부가"],
["Would you mind closing the window?",["Not at all.","It's a nice window.","I closed the deal."],0,"Would you mind ~? → Not at all(괜찮아요) = 수락.","요청·제안"],
["Could you review my presentation slides?",["Sure, send them to me.","It was a great presentation.","I'll slide it over."],0,"요청 수락.","요청·제안"],
["Let's order some pizza for lunch.",["Good idea. I'm starving.","It's in order.","Lunch was yesterday."],0,"제안에 동의.","요청·제안"],
["Why don't you ask Tom for help?",["He's busy with his own project.","Because he asked.","Tom is from Canada."],0,"제안에 반대 이유.","요청·제안"],
["How about meeting at the café downstairs?",["That works for me.","I'll have a latte.","It's downstairs."],0,"제안 수락.","요청·제안"],
["The flight has been canceled.",["Let's book another one.","It's a long flight.","I canceled my order."],0,"문제 상황 → 해결책.","평서문"],
["I left my umbrella at the office.",["You can borrow mine.","It's raining now.","The office is closed."],0,"문제 → 해결책 제시.","평서문"],
["This printer is making a strange noise.",["Let's call the repair service.","Print it twice.","It's very noisy outside."],0,"고장 → 해결책.","평서문"],
["The new intern starts on Monday.",["I'll prepare a desk for her.","Monday is a holiday.","He interned last year."],0,"소식 → 준비 행동.","평서문"],
["We need more volunteers for the charity event.",["I can ask my team.","It was a great event.","The charity is local."],0,"필요 → 도움 제안.","평서문"],
["What's the best way to contact Mr. Silva?",["E-mail usually works best.","He's from Brazil.","Contact lenses."],0,"방법.","의문사"],
["How was your trip to Singapore?",["It was very productive.","By plane.","Next week."],0,"How was → 평가.","의문사"],
["Whose laptop is this?",["I think it's Anna's.","It's very light.","On the desk."],0,"Whose → 소유자.","의문사"],
["Where can I get a copy of the handbook?",["Human Resources has them.","A hundred pages.","I copied it."],0,"사람·부서로 답하는 응답.","의문사"],
["Why are there so many boxes in the hallway?",["We're moving to a new office.","They're in the hallway.","Big boxes."],0,"Why → 이유.","의문사"],
["When's the best time to call you?",["Any time after three.","My number is on the card.","I called yesterday."],0,"When → 시간.","의문사"],
["Who's in charge of ordering supplies?",["That's usually Ms. Kim's job.","Some pens and paper.","In charge of sales."],0,"Who → 사람.","의문사"],
["How long is the flight to Sydney?",["About ten hours.","Next Tuesday.","It's a long way down."],0,"How long → 소요 시간.","의문사"],
["Didn't you already finish the survey?",["I still have two questions left.","It was a survey of customers.","Finish it by Friday."],0,"아직 두 문항 남음.","일반·부정"],
["Shouldn't we leave for the station now?",["The train isn't until four.","The station is new.","We left early."],0,"아직 여유 있다는 간접 응답.","일반·부정"],
["Isn't Mr. Brown retiring this year?",["Not until next spring.","He's tired today.","This year's sales."],0,"‘내년 봄에’ 정정.","일반·부정"],
["Have the new chairs been delivered?",["They should arrive this afternoon.","Please have a seat.","The delivery fee is ten dollars."],0,"아직 아님(오후 도착).","일반·부정"],
["Where did you park the company van?",["Mark was the last one to use it.","In the morning.","The van is white."],0,"‘마크가 마지막으로 썼다’ 간접 응답.","간접"],
["What time does the store open tomorrow?",["It's closed for the holiday.","It's on Main Street.","Open the door."],0,"휴무라는 제3의 응답.","간접"],
["Who should I talk to about my paycheck?",["Payroll is on the fifth floor.","It's paid monthly.","I talked to him."],0,"부서 위치로 답하는 간접 응답.","간접"],
["How much will the repairs cost?",["We're waiting for an estimate.","It's expensive to repair.","Last week."],0,"‘견적 기다리는 중’ 간접 응답.","간접"],
["Which color should we use for the logo?",["What does the client prefer?","It's a new logo.","The color printer."],0,"되묻기 응답.","간접"],
["When are we launching the new app?",["Didn't you see the memo?","The app is free.","Lunch at noon."],0,"되묻기(메모 못 봤어요?) 간접 응답.","간접"],
["Why don't we move the meeting to Friday?",["Several people are off that day.","Because it's Friday.","I moved last year."],0,"제안에 반대 이유.","요청·제안"],
["Could I borrow your stapler?",["It's in the top drawer.","I'll staple it.","He borrowed it."],0,"위치를 알려 주는 수락.","요청·제안"],
["The quarterly report looks great.",["Thanks, the team worked hard on it.","Every quarter.","It's a great place."],0,"칭찬 → 감사.","평서문"],
["I'm thinking of taking the train to Busan.",["That's faster than driving.","I trained him.","Busan is a port city."],0,"의견에 동의 + 이유.","평서문"],
["You've been to our Tokyo office, haven't you?",["Only once, a few years ago.","The office is in Tokyo.","I'll go by plane."],0,"사실 확인.","부가"],
["Would you like a receipt?",["Yes, please.","The recipe is simple.","I received it."],0,"권유 수락. receipt/recipe 유사 발음 함정.","요청·제안"],
["Are the sales figures ready, or do you need more time?",["I need another hour.","The figures are high.","Yes, it's ready."],0,"선택 → 하나 고르기.","선택"]);

G2.push(
["The new safety regulations will be ------ enforced starting next month.",["strict","strictly","strictness","stricter"],1,"품사","수동태 be enforced 사이 부사 자리."],
["Ms. Tanaka gave an ------ presentation on market trends.",["inform","information","informative","informatively"],2,"품사","관사와 명사 사이 형용사."],
["Our goal is to increase customer ------ by 10 percent.",["satisfy","satisfied","satisfaction","satisfying"],2,"품사","명사 customer 뒤 복합명사. customer satisfaction = 고객 만족."],
["The shipment arrived ------ than expected.",["early","earlier","earliest","earliness"],1,"품사","than → 비교급."],
["The manager asked for a ------ report by Friday.",["detail","detailed","detailing","details"],1,"품사","명사 report를 꾸미는 형용사(과거분사형). detailed = 상세한."],
["Employees must complete the training ------ before using the equipment.",["success","successful","successfully","succeed"],2,"품사","동사를 꾸미는 부사."],
["The firm has a strong ------ for quality service.",["reputation","reputable","reputed","reputably"],0,"품사","관사+형용사 뒤 명사."],
["Please handle the glass items with ------.",["care","careful","carefully","cared"],0,"품사","전치사 with 뒤 명사. with care = 조심스럽게."],
["The event was ------ successful, attracting 2,000 visitors.",["remark","remarkable","remarkably","remarking"],2,"품사","형용사 successful을 꾸미는 부사."],
["Applicants should have ------ knowledge of accounting software.",["extend","extensive","extensively","extension"],1,"품사","명사 앞 형용사. extensive knowledge = 폭넓은 지식."],
["The team worked ------ to meet the deadline.",["tireless","tirelessly","tired","tiring"],1,"품사","자동사 worked 뒤 부사."],
["------ of the new branch is scheduled for May.",["Open","The opening","Opened","To opening"],1,"품사","주어 자리 명사. The opening of = ~의 개점."],
["Ms. Lee ------ the company since it was founded.",["leads","led","has led","is leading"],2,"동사","since + 과거 시점 → 현재완료."],
["The documents ------ to you by courier tomorrow.",["send","sent","will be sent","will send"],2,"동사","tomorrow + 문서는 보내지는 것 → 미래 수동."],
["Each of the rooms ------ a view of the ocean.",["offer","offers","offering","have offered"],1,"동사","Each of + 복수명사 → 단수 동사."],
["The CEO suggested that the meeting ------ postponed.",["is","be","was","will be"],1,"동사","suggest that + (should) 동사원형."],
["When the manager arrived, the staff ------ the room.",["already cleaned","had already cleaned","have already cleaned","cleans"],1,"동사","과거(도착)보다 먼저 끝난 일 → 과거완료."],
["The new product ------ well since its launch in March.",["sells","sold","has been selling","will sell"],2,"동사","since + 계속 → 현재완료진행."],
["If I ------ you, I would accept the offer.",["am","was","were","be"],2,"동사","가정법 과거: If I were you."],
["All visitors are required ------ at the front desk.",["sign in","to sign in","signing in","signed in"],1,"동사","be required to do."],
["The number of online orders ------ rising steadily.",["is","are","have","be"],0,"동사","The number of → 단수."],
["A number of employees ------ volunteered for the event.",["has","have","is","was"],1,"동사","A number of + 복수명사 → 복수 동사."],
["The factory ------ by a fire last year, but it has been rebuilt.",["damaged","was damaged","has damaged","damages"],1,"동사","last year + 수동."],
["By the time we arrived, the concert ------.",["already started","had already started","has already started","starts"],1,"동사","By the time + 과거 → 과거완료."],
["------ the rain, the parade continued as planned.",["Although","Despite","Because","Even"],1,"전치사·접속사","뒤에 명사 → 전치사 Despite."],
["The store will be closed ------ Monday and Tuesday.",["on","at","in","by"],0,"전치사·접속사","요일 앞 on."],
["------ you have questions, please contact customer service.",["If","Unless","Whether","Despite"],0,"전치사·접속사","조건 ‘~하면’ If."],
["The package should arrive ------ three business days.",["within","since","during","among"],0,"전치사·접속사","within + 기간 = ~ 이내에."],
["Mr. Park will be out of the office ------ next Wednesday.",["until","by","since","at"],0,"전치사·접속사","부재 상태가 계속 → until."],
["Sales increased ------ the new marketing campaign.",["thanks to","even though","so that","as though"],0,"전치사·접속사","뒤에 명사구 + 원인 → thanks to."],
["Please submit the form ------ fax or e-mail.",["by","with","on","at"],0,"전치사·접속사","수단 by fax/e-mail."],
["The seminar was canceled ------ low registration.",["because","due to","since","as"],1,"전치사·접속사","명사구 앞 전치사구 due to."],
["The report is long; ------, it is easy to read.",["nevertheless","therefore","moreover","otherwise"],0,"전치사·접속사","길다 vs 읽기 쉽다 → 역접 nevertheless."],
["Mr. Cho will attend the meeting ------ his manager is unavailable.",["because","because of","due to","despite"],0,"전치사·접속사","뒤에 절 → 접속사."],
["Keep your receipt ------ you need to return the item.",["in case","in case of","so as","as for"],0,"전치사·접속사","in case + 절 = ~할 경우에 대비해."],
["------ the manager nor the staff knew about the change.",["Either","Neither","Both","Not"],1,"전치사·접속사","neither A nor B."],
["The book ------ you recommended was very useful.",["what","that","who","whose"],1,"관계사·분사","사물 선행사 + 목적격 → that/which."],
["The conference, ------ was held in Busan, attracted many visitors.",["that","which","what","where"],1,"관계사·분사","콤마 뒤 사물 → which."],
["The man ------ car was parked outside is a new client.",["who","whose","whom","which"],1,"관계사·분사","뒤에 명사 car → whose."],
["The city ------ I was born is famous for its seafood.",["which","where","when","what"],1,"관계사·분사","뒤 절 완전 + 장소 → where."],
["------ by the results, the team celebrated.",["Pleasing","Pleased","Please","To please"],1,"관계사·분사","팀이 기쁨을 느낀 것 → Pleased."],
["The ------ deadline caused stress among the staff.",["approach","approaching","approached","approaches"],1,"관계사·분사","다가오는 마감 → approaching(능동)."],
["Visitors ------ the museum must leave their bags at the entrance.",["enter","entering","entered","enters"],1,"관계사·분사","방문객이 들어가는 것 → 능동 -ing."],
["The instructions were ------ to understand.",["confusing","confused","confuse","confusion"],0,"관계사·분사","설명서가 혼란을 주는 것 → confusing."],
["We will visit the factory ------ products are made.",["which","where","what","who"],1,"관계사·분사","장소 + 완전한 절 → where."],
["------ you need is a good night's sleep.",["That","What","Which","Who"],1,"관계사·분사","선행사 없는 ~하는 것 → What."],
["The applicant ------ we interviewed yesterday has accepted the job.",["whom","whose","which","what"],0,"관계사·분사","사람 + 목적격 → whom."],
["Having ------ the report, she sent it to her manager.",["finish","finished","finishing","finishes"],1,"관계사·분사","Having + p.p."],
["This year's profits are ------ higher than last year's.",["very","far","too","so"],1,"비교·대명사","비교급 강조 far."],
["Ms. Kim is the ------ qualified of all the candidates.",["more","most","much","many"],1,"비교·대명사","of all → 최상급."],
["The new model is ------ lighter than the previous one.",["much","many","very","more"],0,"비교·대명사","비교급 강조 much."],
["Please keep ------ belongings with you at all times.",["you","your","yours","yourself"],1,"비교·대명사","명사 앞 소유격."],
["The two companies decided to merge with ------.",["each other","themselves","another","other"],0,"비교·대명사","서로 = each other."],
["This laptop is ------ expensive than the one I bought last year.",["less","least","little","few"],0,"비교·대명사","than → 비교급 less."],
["Mr. Han prepared the presentation ------.",["him","his","himself","he"],2,"비교·대명사","혼자서, 직접 → himself."],
["Of the three proposals, the second one is the ------.",["good","better","best","well"],2,"비교·대명사","셋 중 → 최상급."],
["------ employees must attend the safety training.",["Every","All","Each","Much"],1,"비교·대명사","복수명사 앞 All. Every/Each는 단수명사."],
["The new printer prints twice as ------ as the old one.",["fast","faster","fastest","fastly"],0,"비교·대명사","as ~ as 원급. fastly는 없는 단어."],
["The meeting room is available; ------ can use it.",["anyone","anything","whoever","someone else's"],0,"비교·대명사","사람 누구나 → anyone."],
["The company plans ------ a new branch in Daegu.",["open","to open","opening","opened"],1,"준동사·구문","plan to do."],
["Mr. Lee avoided ------ the question directly.",["answer","to answer","answering","answered"],2,"준동사·구문","avoid -ing."],
["We are looking forward to ------ with you.",["work","working","worked","be working"],1,"준동사·구문","look forward to -ing."],
["The manager let us ------ early on Friday.",["leave","to leave","leaving","left"],0,"준동사·구문","사역 let + 목적어 + 동사원형."],
["Seldom ------ such high sales in December.",["we have seen","have we seen","we saw","seen"],1,"준동사·구문","부정어 문두 도치."],
["The new software is easy ------.",["use","to use","using","used"],1,"준동사·구문","형용사 + to부정사(~하기에)."],
["She stopped ------ coffee because of her health.",["drink","to drink","drinking","drunk"],2,"준동사·구문","stop -ing = ~을 그만두다."],
["It is important ------ your password regularly.",["change","to change","changing","changed"],1,"준동사·구문","It is ~ to do (가주어)."],
["The report needs ------ before it is submitted.",["revise","revising","revised","to revising"],1,"준동사·구문","need -ing = ~될 필요가 있다(수동 의미)."],
["Only then ------ how serious the problem was.",["we realized","did we realize","we did realize","realized we"],1,"준동사·구문","Only then 문두 → 도치."],
["Please remember ------ the lights when you leave.",["turn off","to turn off","turning off","turned off"],1,"준동사·구문","remember to do = (앞으로) ~할 것을 기억하다."],
["The price ------ tax and delivery.",["includes","involves","consists","contains of"],0,"어휘","가격이 ~을 포함하다 = include."],
["Please ------ your seat belt during the flight.",["fasten","tighten","attach","connect"],0,"어휘","fasten a seat belt = 안전벨트를 매다."],
["The company will ------ a new marketing strategy next quarter.",["implement","complement","supplement","compliment"],0,"어휘","implement = 시행하다. 철자 비슷한 단어 함정."],
["Customers are ------ to a 10% discount on their next purchase.",["entitled","allowed","qualified","permitted"],0,"어휘","be entitled to + 명사 = ~을 받을 자격이 있다."],
["The seminar will ------ issues related to workplace safety.",["address","speak","talk","tell"],0,"어휘","address an issue = 문제를 다루다."],
["Please ------ the manager if you have any concerns.",["contact","contact to","reply","respond"],0,"어휘","contact는 타동사(전치사 없이)."],
["The hotel ------ free breakfast to all guests.",["provides","supplies with","gives to","serves for"],0,"어휘","provide + 목적어 = 제공하다."],
["Our store has a wide ------ of products.",["range","scope","field","area"],0,"어휘","a wide range of = 다양한."],
["The company has ------ its sales target for this year.",["reached","arrived","got to","come"],0,"어휘","reach a target = 목표를 달성하다."],
["The flight was delayed ------ to heavy snow.",["due","because","since","instead"],0,"어휘","due to = ~ 때문에. because는 because of, instead는 instead of로 씁니다."],
["The contract will ------ at the end of the year.",["expire","exceed","expose","export"],0,"어휘","계약이 만료되다 = expire."],
["Ms. Oh was ------ as the new head of marketing.",["appointed","applied","approved","appealed"],0,"어휘","appoint A as B = A를 B로 임명하다."]);
