/* batch 002: seed items from the TOEIC Daily Master spec, with translation, vocab and trap analysis */
G2.push(["Ms. Tanaka ------- reviewed the proposed merger contract before presenting it to the board of directors.",["thorough","thoroughly","thoroughness","more thorough"],1,"품사","주어(Ms. Tanaka)와 동사(reviewed) 사이는 동사를 꾸미는 부사 자리입니다. thoroughly가 정답입니다.",{tr:"다나카 씨는 이사회에 제출하기 전에 제안된 합병 계약서를 면밀하게 검토했다.",vo:"thoroughly 철저히, 면밀하게 · proposed merger contract 제안된 합병 계약서 · board of directors 이사회"}]);
G2.push(["All maintenance personnel ------- to wear high-visibility vests while working in the warehouse.",["are required","require","requiring","has required"],0,"동사","주어 personnel은 복수 취급하고, 조끼 착용을 ‘요구받는’ 수동 관계입니다. 뒤에 목적어 없이 to부정사가 바로 오므로 수동태 are required가 정답입니다. has required는 단수 동사라 수가 맞지 않습니다.",{tr:"모든 시설 관리 직원은 창고에서 일하는 동안 눈에 잘 띄는 안전 조끼를 입어야 한다.",vo:"personnel 직원들(복수 취급) · be required to do ~해야 한다 · high-visibility vest 고시인성 안전 조끼"}]);
G2.push(["------- the severe weather conditions, the international courier service delivered all parcels on schedule.",["Although","Despite","Even though","Because"],1,"전치사·접속사","빈칸 뒤가 동사 없는 명사구(the severe weather conditions)이므로 전치사 자리입니다. ‘악천후에도 불구하고’라는 양보의 전치사 Despite가 정답입니다. Although·Even though·Because는 접속사라 뒤에 절이 와야 합니다.",{tr:"심한 악천후에도 불구하고 그 국제 택배 회사는 모든 소포를 예정대로 배달했다.",vo:"despite + 명사 ~에도 불구하고 · courier 택배 회사 · on schedule 예정대로"}]);
G2.push(["The newly renovated auditorium is spacious enough to ------- up to 500 conference attendees.",["accommodate","hesitate","generate","distribute"],0,"어휘","강당이 참석자 500명을 ‘수용하다’라는 의미가 필요합니다. accommodate는 수용 인원을 나타낼 때 쓰는 빈출 타동사입니다. hesitate는 자동사, generate는 ‘창출하다’, distribute는 ‘배포하다’라 문맥에 맞지 않습니다.",{tr:"새로 보수된 강당은 콘퍼런스 참석자를 최대 500명까지 수용할 만큼 넓다.",vo:"accommodate 수용하다 · spacious enough to do ~할 만큼 넓은 · up to 최대 ~까지 · attendee 참석자"}]);
G2.push(["Please ensure that your travel reimbursement forms are submitted ------- two weeks of returning from the business trip.",["within","along","between","through"],0,"전치사·접속사","기간(two weeks)과 함께 쓰여 ‘~ 이내에’를 나타내는 전치사는 within입니다. within + 기간 + of ~ 형태로 ‘~한 지 2주 이내’라는 뜻이 됩니다.",{tr:"출장에서 돌아온 지 2주 이내에 출장비 환급 신청서를 꼭 제출해 주세요.",vo:"within + 기간 ~ 이내에 · reimbursement 환급, 변제 · ensure that ~을 확실히 하다"}]);
P2N.push(["Where should I submit the quarterly expense report?",["To the accounting office on the third floor.","Yes, it was quite expensive.","Every Friday afternoon."],0,"Where 질문에 장소(3층 회계부)로 답한 응답이 정답입니다.","의문사",{tr:"분기 경비 보고서는 어디에 제출해야 하나요?",otr:["3층 회계부에요.","네, 꽤 비쌌어요.","매주 금요일 오후에요."],trap:["","Where 질문에 Yes 응답 불가 + expense–expensive 유사 발음 함정","When(시간)을 물을 때의 응답"],tip:"Where는 장소를 묻습니다. 유사 발음 보기와 Yes/No 보기를 먼저 지우세요."}]);
P2N.push(["Why has the project deadline been postponed?",["At the end of next month.","Because the client requested a few design modifications.","No, I haven't received the mail."],1,"Why 질문에 Because로 이유를 밝힌 응답이 정답입니다.","의문사",{tr:"프로젝트 마감일이 왜 연기되었나요?",otr:["다음 달 말에요.","고객사가 디자인 수정을 몇 가지 요청해서요.","아니요, 우편물을 못 받았어요."],trap:["When(시간)을 물을 때의 응답. deadline에서 시점을 떠올리게 하는 함정","","Why 질문에 No 응답 불가"],tip:"Why는 이유를 묻습니다. Because 외에 To부정사(목적)나 이유를 설명하는 문장도 정답이 됩니다."}]);
P2N.push(["Who is in charge of organizing the upcoming sales convention?",["Mark from human resources is handling it.","The convention center downtown.","They will charge five dollars."],0,"Who 질문에 사람(인사부 마크)으로 답한 응답이 정답입니다.","의문사",{tr:"다가오는 영업 컨벤션 준비는 누가 맡고 있나요?",otr:["인사부의 마크가 맡고 있어요.","시내 컨벤션 센터요.","그들은 5달러를 청구할 거예요."],trap:["","Where(장소)에 대한 응답 + convention 단어 반복 함정","in charge of의 charge를 ‘요금을 청구하다’로 비튼 동음이의어 함정"],tip:"Who 질문은 사람 이름, 직책, 부서가 정답입니다. 질문 단어를 다른 뜻으로 쓴 보기는 함정입니다."}]);
