/* ================= question bank for the in-app drill (no textbook needed) ================= */
/* Part 1: [photo description (ko), statements, answer, explanation] */
const P1B=[
["여자가 계산대에서 점원에게 카드를 건네고 있다",["She's handing a card to a cashier.","She's opening her wallet.","She's stacking some boxes.","She's pushing a shopping cart."],0,"지금 하는 동작은 ‘카드를 건네는 중’. 지갑을 여는 동작은 이미 끝난 상태입니다."],
["남자 둘이 회의실 테이블에 마주 앉아 서류를 보고 있다",["They're arranging some chairs.","They're looking at some documents.","One of the men is writing on a board.","They're shaking hands."],1,"두 사람의 공통 동작은 서류 보기. 사진에 없는 동작(악수, 판서)은 바로 지웁니다."],
["빈 사무실. 책상 위에 모니터 두 대가 있고, 의자는 책상 밑에 밀어 넣어져 있다 (사람 없음)",["A man is using a computer.","Some monitors are being installed.","Chairs have been pushed under a desk.","The desk is being cleaned."],2,"사람 없는 사진에서 is/are being + p.p.(누가 하고 있는 중)는 대부분 오답. have been + p.p.(상태)가 정답."],
["남자가 사다리 위에 서서 천장 전구를 갈고 있다",["He's climbing down a ladder.","He's replacing a light bulb.","He's painting the ceiling.","He's carrying a ladder."],1,"사다리 위에서 전구 교체 중. ladder가 들린다고 고르면 함정(내려가기, 나르기)."],
["가게 선반에 과일 상자가 줄지어 진열돼 있다 (사람 없음)",["Fruit is being picked from trees.","Some boxes are stacked on the floor.","Produce has been displayed on shelves.","A customer is weighing some fruit."],2,"produce = 농산물. has been displayed = 진열돼 있는 상태. 사람 없는 사진의 정답 패턴."],
["여자가 무릎을 꿇고 화분에 물을 주고 있다",["She's watering some plants.","She's planting a tree.","She's buying some flowers.","She's filling a bucket at a sink."],0,"water가 동사로 ‘물을 주다’."],
["부두에 보트 몇 척이 묶여 있다 (사람 없음)",["Some boats are docked at a pier.","People are boarding a ship.","A boat is sailing under a bridge.","Fishermen are unloading nets."],0,"docked at a pier = 부두에 정박해 있다. 사람이 없으니 사람 동작 보기는 모두 오답."],
["여러 사람이 건물 앞 계단을 걸어 내려오고 있다",["They're sitting on some steps.","They're walking down some stairs.","They're entering an elevator.","They're cleaning a staircase."],1,"steps/stairs는 같은 뜻. 앉아 있는 게 아니라 내려오는 중."],
["남자가 복사기 뚜껑을 열고 종이를 올려놓고 있다",["He's repairing a copier.","He's placing a document on a copier.","He's throwing away some paper.","He's filing some folders."],1,"place = 놓다. 복사기를 고치는 게 아니라 문서를 올려놓는 중."],
["식당 테이블에 접시와 컵이 차려져 있고 의자는 비어 있다",["Diners are ordering food.","A server is pouring water.","Tables have been set for a meal.","Chairs are being stacked."],2,"set a table = 상을 차리다. 사람 없음 + have been p.p. 패턴."],
["여자가 선반 높은 곳의 책을 꺼내려고 손을 뻗고 있다",["She's reaching for a book.","She's reading at a desk.","She's putting on her glasses.","She's standing on a chair."],0,"reach for = ~을 잡으려고 손을 뻗다. Part 1 단골 동사."],
["공사장에서 안전모를 쓴 작업자 두 명이 철근을 옮기고 있다",["They're taking off their helmets.","They're carrying some building materials.","They're sitting in a truck.","They're painting a wall."],1,"철근 → building materials로 바꿔 말함. take off(벗는 동작)는 사진과 다름."],
["주차장에 차들이 한 줄로 주차돼 있고 나무 그늘이 져 있다 (사람 없음)",["Cars are parked in a row.","Trees are being cut down.","A car is being washed.","A driver is opening a trunk."],0,"in a row = 한 줄로. 사람 없는 사진이라 being + p.p.와 운전자 보기는 오답."],
["남자가 노트북 앞에서 헤드셋을 쓰고 통화하고 있다",["He's taking off a headset.","He's wearing a headset.","He's plugging in a laptop.","He's closing a laptop."],1,"wear(착용 상태) vs put on/take off(입고 벗는 동작) 구분은 Part 1 단골 함정."],
["창고 바닥에 상자들이 여러 층으로 쌓여 있다 (사람 없음)",["Boxes are being loaded onto a truck.","Some boxes have been stacked on the floor.","A worker is opening a box.","Shelves are empty."],1,"stack = 쌓다. have been stacked = 쌓여 있는 상태."],
["여자 둘이 공원 벤치에 앉아 신문을 읽고 있다",["They're reading newspapers on a bench.","They're painting a bench.","They're jogging in a park.","They're feeding some birds."],0,"사진 그대로의 동작. bench, park가 들려도 동작이 틀리면 오답."],
["남자가 자전거를 끌고 횡단보도를 건너고 있다",["He's riding a bicycle on a trail.","He's repairing a bicycle tire.","He's walking a bicycle across a street.","He's locking a bicycle to a rack."],2,"walk a bicycle = 자전거를 끌고 걷다. 타고 있는(riding) 게 아님."],
["호텔 로비. 소파와 스탠드가 있고 벽에 그림이 걸려 있다 (사람 없음)",["A picture is being hung on the wall.","Artwork is mounted on a wall.","Guests are checking in.","A lamp is being turned on."],1,"mounted = 걸려 있는(상태). is being hung은 누가 거는 중이라 사람이 필요."],
["요리사가 주방에서 채소를 썰고 있다",["A chef is chopping vegetables.","A chef is washing dishes.","A chef is tasting soup.","Vegetables are being delivered."],0,"chop = 잘게 썰다."],
["여자가 화이트보드의 그래프를 가리키며 발표하고, 몇 사람이 앉아서 듣고 있다",["The audience is leaving the room.","A woman is erasing a whiteboard.","A woman is pointing at a chart.","Some people are setting up chairs."],2,"point at = 가리키다. 그래프 → chart."]];

/* Part 2 additions: [question, responses, answer, explanation, tag] */
const P2N=[
["Where is the nearest post office?",["It's just around the corner.","By express mail.","Yes, I posted it."],0,"Where는 장소. 의문사 의문문에 Yes로 답하는 보기와 post 반복은 함정.","의문사"],
["When will the new manager start?",["In the marketing department.","Not until next month.","He's very experienced."],1,"When은 시점. Not until next month = 다음 달이 되어서야.","의문사"],
["Who ordered these office supplies?",["At the supply store.","Twenty boxes.","I think it was Ms. Choi."],2,"Who는 사람. supplies/supply 반복은 함정.","의문사"],
["Why is the parking lot so crowded today?",["There's a special event downstairs.","I parked my car.","About fifty spaces."],0,"Why에 Because 없이 이유만 말해도 정답. park 반복은 함정.","의문사"],
["How often do you back up your files?",["In the back office.","Once a week.","A new file cabinet."],1,"How often은 빈도. back, file 반복은 함정.","의문사"],
["What did you think of the new logo?",["It looks much more modern.","I'll think about it.","At the design team meeting."],0,"의견을 묻는 질문. think 반복은 함정.","의문사"],
["How much does it cost to rent a car for a day?",["It's parked outside.","About sixty dollars.","For two days."],1,"How much는 가격. day 반복은 함정.","의문사"],
["Which printer should I use?",["The one in the hallway works best.","Twenty copies, please.","Yes, you should."],0,"Which에는 the one ~ 응답이 단골 정답.","의문사"],
["Where can I find the updated sales figures?",["They went up by ten percent.","Ask Mr. Park in accounting.","I found it yesterday."],1,"장소 대신 ‘누구에게 물어보라’는 간접 응답.","간접"],
["When is the deadline for the budget proposal?",["It hasn't been decided yet.","A budget hotel.","He proposed it."],0,"‘아직 정해지지 않았다’는 거의 모든 질문에 통하는 간접 응답.","간접"],
["Who's going to pick up the clients at the airport?",["Terminal 2.","Let's check the schedule.","They picked the red one."],1,"‘일정표를 확인해 보자’는 간접 응답. pick 반복은 함정.","간접"],
["Did you finish the inventory report?",["I still need to count the items in storage.","The report was on the desk.","A new inventory system."],0,"아직 못 끝냈다는 간접 응답. report, inventory 반복은 함정.","일반·부정"],
["Is the conference room available this afternoon?",["It's being used until three.","I'll be available.","A large conference."],0,"3시까지는 사용 중이라는 조건부 응답.","일반·부정"],
["Didn't Ms. Moore approve the budget already?",["Budget airlines are popular.","She's still reviewing it.","Yes, a proof of purchase."],1,"부정 의문문은 긍정 의문문처럼 풀면 됩니다. ‘아직 검토 중’이 정답.","일반·부정"],
["Have you been to the new branch office?",["I'm going there on Friday.","A branch of the tree.","It's been a while."],0,"아직 안 가 봤지만 금요일에 간다는 응답. branch(지점/나뭇가지) 다의어 함정.","일반·부정"],
["Aren't you coming to the retirement party?",["He's retiring next week.","I have to work late tonight.","The party room is upstairs."],1,"못 가는 이유를 말하는 간접 응답.","일반·부정"],
["Will the store be open on the holiday?",["Only in the morning.","Open the box, please.","I hope you enjoyed it."],0,"오전만 연다는 조건부 응답. open 반복은 함정.","일반·부정"],
["Can I pay with a credit card?",["I'll pay you back.","Sorry, cash only.","The card was sent."],1,"가능 여부 질문에 ‘현금만 됩니다’라는 거절. pay, card 반복은 함정.","요청·제안"],
["The shipment should arrive by Thursday, right?",["That's what the supplier told me.","The ship left port.","On Thursday afternoons."],0,"사실 확인 질문. ship/shipment 비슷한 소리는 함정.","부가"],
["You're attending the trade show, aren't you?",["The show was great.","I haven't registered yet.","Trade agreements."],1,"‘아직 등록 안 했다’는 간접 응답.","부가"],
["This is the latest version of the contract, isn't it?",["No, I'm late.","Mr. Lee has the newest one.","A two-year contract."],1,"최신본은 다른 사람이 갖고 있다 = 이건 최신본이 아니라는 뜻. late/latest는 함정.","부가"],
["The meeting has been moved to Room 5, hasn't it?",["Yes, because Room 3 is being painted.","We're moving next month.","Five people."],0,"Yes + 이유. move, five 반복은 함정.","부가"],
["Would you prefer a window or an aisle seat?",["I don't mind either.","The window is open.","Yes, I would."],0,"선택 의문문에 ‘둘 다 괜찮다’는 단골 정답. Yes/No는 거의 오답.","선택"],
["Should I call the client or send an e-mail?",["She called yesterday.","An e-mail would be better.","The client list."],1,"선택 의문문 → 둘 중 하나를 고른 응답.","선택"],
["Is the workshop on Friday or Saturday?",["It's been canceled.","Yes, it's fun.","About two hours."],0,"둘 다 아닌 제3의 응답(‘취소됐다’)도 정답이 됩니다.","선택"],
["Do you want to take the train or drive to Busan?",["The train station.","Driving takes too long.","I trained the new staff."],1,"‘운전은 너무 오래 걸린다’ = 기차를 고른 간접 응답. train(기차/교육하다) 다의어 함정.","선택"],
["Could you help me move these boxes?",["Sure, where do they go?","They moved last year.","A box of paper."],0,"요청에 수락 + 되묻기.","요청·제안"],
["Why don't you take tomorrow off?",["I'd like to, but we have a deadline.","He took it off.","Because it's tomorrow."],0,"Why don't you는 이유가 아니라 제안. Because로 시작하는 보기는 함정.","요청·제안"],
["Would you like some more coffee?",["No, thanks. I've had enough.","The coffee shop is closed.","I like it very much."],0,"권유에는 수락이나 거절.","요청·제안"],
["Let's review the proposal after lunch.",["Good idea. I'll bring my notes.","I had a sandwich.","It was a great review."],0,"제안하는 평서문에는 동의나 반대.","요청·제안"],
["Can you show me how to use the new scanner?",["It's a new model.","I'm actually on my way to a meeting.","Show me your ticket."],1,"지금 회의 가는 중 = 거절의 간접 응답.","요청·제안"],
["How about hiring a temporary assistant?",["Let's see if the budget allows it.","He was hired last year.","It's temporary."],0,"How about은 제안. ‘예산부터 보자’는 유보 응답.","요청·제안"],
["I can't find my security badge.",["Did you check your car?","It's very secure.","Badges are required."],0,"문제 상황을 말하는 평서문에는 해결책이나 되묻기.","평서문"],
["The sales numbers look better this quarter.",["Yes, the new ads really helped.","Look at the numbers.","In the last quarter."],0,"의견에는 동의 + 이유.","평서문"],
["We're running out of printer paper.",["I'll order some more today.","He ran in the marathon.","Print it in color."],0,"문제 제기에는 해결책. run 반복은 함정.","평서문"],
["The air conditioner in my office isn't working.",["I'll contact maintenance.","It's working hours.","The office is on the second floor."],0,"고장 신고에는 해결책. working 반복은 함정.","평서문"],
["I heard the company picnic has been postponed.",["Yes, because of the rain forecast.","A picnic basket.","I didn't hear it ring."],0,"들은 소식에 확인 + 이유.","평서문"],
["Ms. Kim will be transferred to the London office.",["The transfer fee is high.","When does she leave?","I've been to London."],1,"평서문에 되묻는 응답이 정답인 경우가 많습니다.","평서문"],
["Where should we hold the year-end party?",["How about the hotel downtown?","At the end of the year.","Hold on a minute."],0,"Where 질문에 How about ~?로 되묻는 제안 응답.","간접"],
["Who's responsible for updating the Web site?",["That job was given to an outside firm.","The site is very popular.","Update it tomorrow."],0,"사람 이름 대신 ‘외부 업체’로 답하는 응답.","간접"],
["Why hasn't the report been sent out yet?",["Mr. Chen is still checking the figures.","By e-mail.","A few reports."],0,"Why에는 이유(아직 검토 중).","의문사"],
["How did you hear about our company?",["A friend recommended it.","I can't hear you well.","It's a large company."],0,"How는 방법·경로. hear 반복은 함정.","의문사"],
["When does the museum close today?",["I'll look it up online.","The closest museum.","It was closed last week."],0,"‘찾아볼게요’는 간접 응답. close/closest는 함정.","간접"],
["What's the fastest way to the convention center?",["Take the subway on Line 2.","It's the fastest car.","The convention lasts three days."],0,"가는 방법을 묻는 질문.","의문사"],
["Whose turn is it to make coffee?",["I made it this morning.","Turn left at the corner.","It's hot coffee."],0,"‘아침엔 내가 했다’ = 내 차례가 아니라는 간접 응답. turn 다의어 함정.","간접"],
["How long has Mr. Diaz worked here?",["Since 2018, I believe.","It's a long way.","He works hard."],0,"How long은 기간. since + 시작 시점.","의문사"],
["Isn't the report due today?",["The deadline was extended.","He's reporting live.","It's due to the rain."],0,"마감이 연장됐다는 간접 응답. due 다의어 함정.","일반·부정"],
["Has the new projector been installed?",["The technician is coming at two.","Project management.","Install the app first."],0,"아직 안 됐다는 간접 응답(기사가 2시에 온다).","일반·부정"],
["Do you know where the staff meeting is?",["It's in the lounge on the third floor.","Yes, I know him.","Nice to meet you."],0,"Do you know where ~는 사실상 Where 질문.","일반·부정"],
["You've submitted your expense report, haven't you?",["Not yet. I'm missing one receipt.","It was expensive.","Report to the manager."],0,"Not yet + 이유. expense/expensive는 함정.","부가"],
["Would you rather have the meeting now or later?",["Now works for me.","The meeting ran late.","I'd rather not."],0,"선택 의문문 → 하나를 고른 응답.","선택"],
["Should we order lunch in or eat out?",["The order was shipped.","It's out of order.","Let's decide after the call."],2,"‘통화 끝나고 정하자’는 유보 응답. order 다의어 함정.","선택"],
["Could you send me a copy of the agenda?",["I'll forward it to you now.","Five copies.","He sent a card."],0,"요청에 수락. copy, send 반복은 함정.","요청·제안"],
["Why don't we ask Ms. Lee for her opinion?",["She's out of the office this week.","Because she asked.","It's my opinion."],0,"제안에 ‘이번 주 부재중’이라는 반대 이유.","요청·제안"],
["The client wants to change the delivery date.",["To which day?","It's a new client.","Deliver it by hand."],0,"평서문에 되묻는 응답.","평서문"],
["I think we need more chairs for the seminar.",["I'll get some from the storage room.","It was a good seminar.","Please have a seat."],0,"의견에 해결책으로 응답.","평서문"],
["What time is our flight to Tokyo?",["It leaves at 7:40.","Flight 202.","A two-hour trip."],0,"What time은 시각. 편명이나 소요 시간은 오답.","의문사"],
["Where did you buy that jacket?",["It was a gift from my sister.","It fits well.","Last weekend."],0,"산 곳 대신 ‘선물 받았다’는 간접 응답.","간접"],
["Who should I send the invoice to?",["The accounting department handles that.","It's in the voice mail.","Next Tuesday."],0,"사람 대신 부서로 답하는 응답. invoice/voice 비슷한 소리 함정.","의문사"],
["Why was the train delayed?",["There was a signal problem.","It was delayed by an hour.","Platform 3."],0,"Why에는 이유. delayed 반복은 이유가 아님.","의문사"]];
const P2TAG=["의문사","의문사","의문사","요청·제안","요청·제안","일반·부정","선택","평서문","의문사","부가","의문사","간접","요청·제안","일반·부정","의문사","간접","평서문","선택","의문사","부가"];

/* Part 5 additions: [sentence, options, answer, type, explanation] */
const G2=[
["The contract must be signed and returned ------ to avoid delays.",["prompt","prompter","promptly","promptness"],2,"품사","동사 returned를 꾸미는 부사 promptly(즉시)."],
["Our technicians provide ------ support to all clients 24 hours a day.",["technical","technically","technician","technique"],0,"품사","명사 support 앞은 형용사 자리. technical support = 기술 지원."],
["The ------ of the new factory will create about 200 jobs.",["construct","constructive","construction","constructed"],2,"품사","관사 The와 전치사 of 사이는 명사 자리."],
["Ms. Rivera was ------ pleased with the results of the survey.",["extreme","extremely","extremity","extremes"],1,"품사","형용사 pleased를 꾸미는 부사."],
["The hotel's staff are known for being ------ to guests' needs.",["attend","attentive","attention","attentively"],1,"품사","being 뒤 보어 자리는 형용사. be attentive to = ~에 세심하다."],
["Management has made a ------ decision to open two more branches.",["strategy","strategic","strategically","strategize"],1,"품사","관사 a와 명사 decision 사이는 형용사 자리."],
["Visitors must show ------ before entering the laboratory.",["identify","identifiable","identification","identified"],2,"품사","동사 show의 목적어 자리는 명사. identification = 신분증."],
["Sales of electric bicycles have risen ------ over the past two years.",["steady","steadily","steadiness","steadied"],1,"품사","자동사 have risen 뒤에서 꾸미는 부사."],
["The committee found the proposal ------ and approved it immediately.",["persuade","persuasion","persuasive","persuasively"],2,"품사","find + 목적어 + 형용사 보어. 부사는 보어가 될 수 없습니다."],
["Mr. Han is one of the most ------ engineers in the department.",["experience","experienced","experiencing","experiences"],1,"품사","the most와 명사 사이 형용사. 사람이 ‘경험 많은’ = experienced."],
["The new design is ------ different from the previous model.",["significant","significantly","significance","signify"],1,"품사","형용사 different를 꾸미는 부사."],
["All employees should read the safety manual ------.",["careful","carefully","care","carefulness"],1,"품사","완전한 문장 끝에서 동사 read를 꾸미는 부사."],
["Thank you for your ------ in our customer satisfaction survey.",["participate","participant","participation","participatory"],2,"품사","소유격 your 뒤 명사 자리. 참가자(사람)가 아니라 ‘참여’(행위)."],
["Mr. Allen ------ for the company for over ten years before he retired last month.",["works","has worked","had worked","will work"],2,"동사","은퇴(과거)보다 더 이전부터 이어진 일 → 과거완료 had worked."],
["The package ------ yesterday, but no one was at the office to receive it.",["delivers","was delivered","is delivering","has delivered"],1,"동사","yesterday(과거) + 소포는 배달‘되는’ 것 → was delivered."],
["Currently, the IT team ------ the new security system.",["tests","tested","is testing","has been tested"],2,"동사","Currently(지금)는 현재진행과 짝. 팀이 테스트하는 주체라 능동."],
["If Ms. Grant ------ available tomorrow, she will lead the orientation.",["is","will be","was","were"],0,"동사","조건을 나타내는 if절은 미래 일이라도 현재시제."],
["The new regulations ------ into effect next month.",["come","came","will come","have come"],2,"동사","next month는 미래. 주절이므로 will come."],
["Several complaints ------ about the noise from the construction site.",["have received","have been received","receiving","receives"],1,"동사","불만은 접수‘되는’ 것이고 뒤에 목적어가 없으므로 수동태."],
["It is essential that every participant ------ the form before the workshop.",["completes","complete","completed","will complete"],1,"동사","essential, important, necessary + that절은 (should) 동사원형."],
["The shipment of office chairs ------ expected to arrive on Thursday.",["are","is","were","being"],1,"동사","주어의 핵심은 shipment(단수). of office chairs는 꾸미는 말."],
["By next March, Dr. Moon ------ at the research institute for five years.",["works","has worked","will have worked","worked"],2,"동사","By + 미래 시점 + for 기간 → 미래완료."],
["The director had her assistant ------ the meeting room for the afternoon.",["reserve","reserved","reserving","to reserve"],0,"동사","사역동사 have + 사람 + 동사원형."],
["Neither of the candidates ------ the required experience.",["have","has","having","are having"],1,"동사","neither of + 복수명사는 토익에서 단수 취급."],
["The quarterly figures ------ to the board last Friday.",["present","were presented","have presented","presenting"],1,"동사","last Friday(과거) + 수치는 보고‘되는’ 것 → 과거 수동."],
["Had we known about the delay, we ------ a later flight.",["would book","would have booked","had booked","will book"],1,"동사","Had we known = If we had known(가정법 과거완료 도치) → would have p.p."],
["The library will remain open ------ the renovation work.",["during","while","when","unless"],0,"전치사·접속사","뒤에 명사구 → 전치사. ‘~ 동안’ during. while은 접속사."],
["------ the new software is installed, employees will attend a training session.",["Once","Despite","Due to","In order to"],0,"전치사·접속사","뒤에 주어 + 동사 → 접속사. Once = 일단 ~하면."],
["The meeting was canceled ------ the manager was ill.",["because of","because","due to","owing to"],1,"전치사·접속사","뒤에 절이 오므로 접속사 because. 나머지는 전치사(구)."],
["Applicants must have a degree in engineering ------ equivalent experience.",["or","nor","but","so"],0,"전치사·접속사","‘학위 또는 그에 준하는 경력’ → or."],
["------ submitting your application, please double-check all the information.",["Before","Until","Since then","As soon"],0,"전치사·접속사","Before -ing = ~하기 전에."],
["The store offers free delivery ------ orders over $50.",["on","at","in","to"],0,"전치사·접속사","free delivery on orders = ~ 주문에 대한 무료 배송. 짝으로 외우기."],
["Ms. Tan will be in charge ------ Mr. Harris is on leave.",["while","during","for","by"],0,"전치사·접속사","뒤에 절 → 접속사 while."],
["The project was completed on time ------ several unexpected problems.",["although","in spite of","even though","whereas"],1,"전치사·접속사","뒤에 명사구 → 전치사구 in spite of. 나머지는 접속사."],
["Please turn off all the lights ------ you leave the office.",["before","after all","prior to","as well as"],0,"전치사·접속사","뒤에 절 → 접속사 before. prior to는 전치사."],
["The factory tour will take place ------ 10 A.M. and noon.",["between","among","from","within"],0,"전치사·접속사","between A and B."],
["Participants can register ------ by phone or online.",["both","either","neither","whether"],1,"전치사·접속사","either A or B."],
["The sales team exceeded its target; ------, all members will receive a bonus.",["however","therefore","otherwise","nevertheless"],1,"전치사·접속사","목표 초과(원인) → 보너스(결과). therefore."],
["The seminar is open to all staff ------ their department.",["regardless of","in case","as if","even if"],0,"전치사·접속사","뒤에 명사구 → 전치사구 regardless of(~와 상관없이)."],
["The employee ------ proposal was selected will receive a gift card.",["who","whose","whom","which"],1,"관계사·분사","뒤에 명사 proposal이 바로 오므로 소유격 whose."],
["The ------ changes to the schedule will be announced tomorrow.",["proposing","proposed","propose","proposes"],1,"관계사·분사","변경 사항은 제안‘된’ 것 → 과거분사."],
["Anyone ------ in volunteering should contact Ms. Diaz.",["interesting","interested","interest","interests"],1,"관계사·분사","사람이 관심을 ‘느끼는’ 것 → interested."],
["The results of the customer survey were ------.",["disappointing","disappointed","disappoint","disappointedly"],0,"관계사·분사","결과가 실망을 ‘주는’ 것 → -ing. 사람이 실망하면 disappointed."],
["This is the hotel ------ we stayed during the conference.",["which","where","what","whose"],1,"관계사·분사","뒤 절이 완전하고(we stayed) 선행사가 장소 → 관계부사 where."],
["------ the report, Ms. Lin found several errors.",["Reviewing","Reviewed","To be reviewed","Review"],0,"관계사·분사","Ms. Lin이 검토하는 주체 → 능동 분사구문."],
["Items ------ during the sale cannot be returned or exchanged.",["purchase","purchasing","purchased","purchases"],2,"관계사·분사","물건은 구매‘되는’ 것 → purchased."],
["The company, ------ headquarters are in Seoul, has offices in 12 countries.",["which","whose","that","its"],1,"관계사·분사","콤마 뒤 + 명사 headquarters → 소유격 관계대명사 whose."],
["Please follow the instructions ------ in the user manual.",["describing","described","describe","to describe"],1,"관계사·분사","설명‘된’ 지시사항 → described."],
["The reason ------ the flight was delayed has not been announced.",["why","which","how","what"],0,"관계사·분사","the reason + 완전한 절 → 관계부사 why."],
["Our new assistant, ------ joined us last week, speaks three languages.",["who","that","whom","which"],0,"관계사·분사","사람 선행사 + 콤마 뒤 주격 → who. 계속적 용법에 that은 불가."],
["When ------ about the delay, the manager apologized to the customers.",["asking","asked","ask","to ask"],1,"관계사·분사","매니저가 질문을 ‘받은’ 것 → When (he was) asked."],
["------ is most important to our clients is reliable service.",["That","What","Which","It"],1,"관계사·분사","빈칸~clients가 주어이고 선행사가 없음 → What(~하는 것)."],
["This year's revenue was twice as high ------ last year's.",["as","than","so","that"],0,"비교·대명사","twice as + 원급 + as."],
["Of all the applicants, Ms. Wu has the ------ experience.",["much","more","most","many"],2,"비교·대명사","Of all ~ + the → 최상급 most."],
["The new printer is ------ faster than the old one.",["very","even","so","too"],1,"비교·대명사","비교급 강조는 even, much, far, still. very는 불가."],
["Employees must submit ------ timesheets by Friday.",["they","their","them","theirs"],1,"비교·대명사","명사 timesheets 앞은 소유격."],
["The managers discussed the issue among ------.",["them","their","themselves","they"],2,"비교·대명사","주어(The managers)와 같은 대상 → 재귀대명사."],
["The more you practice, the ------ you will become.",["confident","more confident","most confident","confidently"],1,"비교·대명사","The 비교급 ~, the 비교급 …"],
["Each department has ------ own budget.",["its","their","it's","it"],0,"비교·대명사","Each department는 단수 → its. it's는 it is."],
["Some clients prefer e-mail, while ------ prefer phone calls.",["another","other","others","the other"],2,"비교·대명사","some ~, others ~. other는 단독으로 명사 역할을 못 합니다."],
["Mr. Cho's presentation was as ------ as Ms. Kim's.",["impressive","more impressive","most impressive","impressively"],0,"비교·대명사","as ~ as 사이에는 원급. be동사 보어라 형용사."],
["There were ------ people at the seminar than we had expected.",["less","fewer","few","little"],1,"비교·대명사","people은 셀 수 있는 복수 + than → fewer."],
["We have received ------ inquiries about the new product.",["a number of","the number of","an amount of","much"],0,"비교·대명사","a number of + 복수명사 = 많은. amount, much는 셀 수 없는 명사에."],
["Ms. Patel handled the negotiations ------, without any help from her team.",["she","her","hers","herself"],3,"비교·대명사","문장이 이미 완전 → 강조의 재귀대명사 herself(직접)."],
["Of the two hotels, the one near the station is ------ expensive.",["less","the less","least","the least"],1,"비교·대명사","Of the two ~ 구문에서는 the + 비교급."],
["The manager decided ------ the launch until next month.",["postpone","postponing","to postpone","postponed"],2,"준동사·구문","decide는 to부정사를 목적어로 받습니다."],
["We look forward to ------ you at the conference.",["see","seeing","seen","be seeing"],1,"준동사·구문","look forward to의 to는 전치사 → 동명사."],
["The company is committed to ------ its environmental impact.",["reduce","reducing","reduced","reduces"],1,"준동사·구문","be committed to + -ing (to는 전치사)."],
["Mr. Lopez stopped by the office ------ his documents.",["pick up","to pick up","picked up","picks up"],1,"준동사·구문","‘~하려고’(목적) → to부정사."],
["Not only ------ the sales target, but it also reduced costs.",["the team met","did the team meet","the team did meet","met the team"],1,"준동사·구문","Not only가 문장 앞 → 조동사 + 주어 + 동사원형으로 도치."],
["The software is too complex ------ in one day.",["learn","to learn","learning","for learn"],1,"준동사·구문","too + 형용사 + to부정사 = 너무 ~해서 …할 수 없다."],
["Would you mind ------ the door?",["close","closing","to close","closed"],1,"준동사·구문","mind는 동명사를 목적어로."],
["The new system enables employees ------ their schedules online.",["manage","managing","to manage","managed"],2,"준동사·구문","enable A to do."],
["Rarely ------ such a positive response to a new product.",["we have seen","have we seen","we saw","seen we have"],1,"준동사·구문","부정어 Rarely가 문장 앞 → 도치."],
["The workshop is designed ------ managers improve their communication skills.",["help","to help","helping","helped"],1,"준동사·구문","be designed to do."],
["It is worth ------ the extra fee for express delivery.",["pay","paying","to pay","paid"],1,"준동사·구문","be worth -ing = ~할 가치가 있다."],
["The CEO had no choice but ------ the plant.",["close","closing","to close","closed"],2,"준동사·구문","have no choice but to do."],
["Please ------ the attached file for details about the event.",["refer","consult","look","inform"],1,"어휘","consult + 목적어 = 참고하다. refer는 refer to, look은 look at이 필요."],
["The hotel is ------ located near the airport and the convention center.",["conveniently","comfortably","eagerly","previously"],0,"어휘","conveniently located = 편리한 곳에 위치한."],
["The warranty is ------ for two years from the date of purchase.",["valid","eligible","capable","accurate"],0,"어휘","보증·계약이 ‘유효하다’ = valid."],
["Customers can ------ their points for discounts on future purchases.",["redeem","remove","remind","resume"],0,"어휘","redeem points = 포인트를 사용(교환)하다."],
["The CEO will ------ the opening ceremony next Monday.",["attend","participate","attract","apply"],0,"어휘","attend + 목적어. participate는 participate in."],
["The company has decided to ------ its contract with the supplier for another year.",["extend","expand","exceed","expose"],0,"어휘","extend a contract = 계약을 연장하다."],
["All staff are required to wear protective ------ in the laboratory.",["equipment","instrument","facility","reservation"],0,"어휘","protective equipment = 보호 장비."],
["Our sales representatives are ------ to answer your questions.",["available","possible","probable","capable"],0,"어휘","사람이 ‘응대할 수 있는’ = available. possible은 사람 주어로 쓰지 않습니다."],
["The new policy will ------ all employees, including part-time staff.",["affect","effect","afford","adopt"],0,"어휘","affect(동사) = 영향을 미치다. effect는 주로 명사."],
["Please ------ from smoking anywhere on the premises.",["refrain","prevent","prohibit","avoid"],0,"어휘","refrain from -ing. prevent, prohibit은 목적어가 필요하고 avoid는 바로 -ing."],
["The report provides a ------ overview of the market trends.",["comprehensive","comprehensible","compressed","comprehending"],0,"어휘","comprehensive = 포괄적인. comprehensible(이해할 수 있는)과 구별."],
["Ms. Yoon was ------ to the position of marketing director.",["promoted","advanced","raised","lifted"],0,"어휘","be promoted to + 직책 = 승진하다."],
["Prices are ------ to change without prior notice.",["subject","eligible","open","due"],0,"어휘","be subject to change = 변경될 수 있다."]];
