/* card extras for the word list: VX[word]=[품사, 짝꿍 표현, 예문, 예문 해석]. Add more with Object.assign(VX,{...}). */
Object.assign(VX,{
"accommodate":["동사","accommodate the growing demand","The newly built hotel can accommodate over 400 guests comfortably.","새로 지은 호텔은 400명 이상의 투숙객을 편안하게 수용할 수 있다."],
"acquire":["동사","acquire a competitor","Harlow Foods plans to acquire a smaller rival by the end of the year.","할로우 푸드는 연말까지 더 작은 경쟁사를 인수할 계획이다."],
"adjacent":["형용사","adjacent to the lobby","The meeting room adjacent to the lobby has been reserved for the interviews.","로비 옆 회의실이 면접용으로 예약되었다."],
"agenda":["명사","the first item on the agenda","The budget review is the first item on the agenda.","예산 검토가 안건의 첫 번째 항목이다."],
"allocate":["동사","allocate funds for","The city allocated additional funds for road repairs.","시는 도로 보수에 추가 자금을 배정했다."],
"amenity":["명사","hotel amenities","Guests can enjoy amenities such as a pool and a fitness center.","투숙객은 수영장과 피트니스 센터 같은 편의시설을 이용할 수 있다."],
"anticipate":["동사","anticipate an increase in","We anticipate an increase in sales during the holiday season.","우리는 연휴 기간에 매출이 늘 것으로 예상한다."],
"applicant":["명사","qualified applicants","Only qualified applicants will be contacted for an interview.","자격을 갖춘 지원자에게만 면접 연락을 드립니다."],
"appoint":["동사","be appointed (as) director","Ms. Ruiz was appointed as the new marketing director.","루이즈 씨가 새 마케팅 이사로 임명되었다."],
"approximately":["부사","approximately 30 minutes","The tour lasts approximately 30 minutes.","투어는 약 30분 걸린다."],
"attire":["명사","business attire","Business attire is required at the awards dinner.","시상식 만찬에는 비즈니스 정장이 필요하다."],
"authorize":["동사","authorize a payment","Only the finance manager can authorize payments over $5,000.","5천 달러가 넘는 지급은 재무 관리자만 승인할 수 있다."],
"available":["형용사","be available for","Mr. Chen is not available for a meeting until Thursday.","첸 씨는 목요일까지 회의할 시간이 없다."],
"beverage":["명사","food and beverages","Food and beverages are not permitted in the library.","도서관 안에는 음식과 음료를 반입할 수 없다."],
"brochure":["명사","a product brochure","Please take a product brochure on your way out.","나가실 때 제품 안내 책자를 가져가세요."],
"budget":["명사","within budget","The renovation was completed on time and within budget.","보수 공사는 제시간에 예산 안에서 끝났다."],
"candidate":["명사","a candidate for the position","Three candidates for the position will be interviewed on Monday.","그 직책의 후보자 세 명이 월요일에 면접을 본다."],
"comply with":["동사구","comply with safety regulations","All visitors must comply with the plant's safety regulations.","모든 방문객은 공장의 안전 규정을 준수해야 한다."],
"complimentary":["형용사","complimentary breakfast","All rooms include a complimentary breakfast.","모든 객실에 무료 조식이 포함된다."],
"confidential":["형용사","strictly confidential document","All personnel records must be kept in a strictly confidential file.","모든 인사 기록은 엄격한 기밀 문서함에 보관해야 한다."],
"consecutive":["형용사","for the third consecutive year","The company posted record profits for the third consecutive year.","그 회사는 3년 연속 사상 최대 이익을 냈다."],
"contract":["명사","sign a contract","Both parties signed the contract on Friday.","양측은 금요일에 계약서에 서명했다."],
"coordinate":["동사","coordinate with","Please coordinate with the IT team before installing new software.","새 소프트웨어를 설치하기 전에 IT 팀과 조율하세요."],
"courier":["명사","by courier","The signed documents were sent by courier this morning.","서명된 서류는 오늘 아침 택배로 발송되었다."],
"defective":["형용사","defective merchandise","Defective merchandise may be returned for a full refund.","결함 있는 상품은 반품하고 전액 환불받을 수 있다."],
"delegate":["동사","delegate tasks to","Good managers delegate routine tasks to their staff.","좋은 관리자는 일상 업무를 직원에게 위임한다."],
"deadline":["명사","meet the deadline","The team worked overtime to meet the deadline.","팀은 마감일을 맞추려고 초과 근무를 했다."],
"dedicated":["형용사","be dedicated to","The firm is dedicated to providing excellent service.","그 회사는 훌륭한 서비스를 제공하는 데 전념한다."],
"deposit":["명사","a security deposit","A security deposit of one month's rent is required.","한 달 치 임대료의 보증금이 필요하다."],
"distribute":["동사","distribute handouts to","The speaker distributed handouts to all participants.","발표자는 모든 참가자에게 유인물을 나눠 주었다."],
"durable":["형용사","durable materials","The backpacks are made from durable, waterproof materials.","그 배낭은 튼튼한 방수 소재로 만들어졌다."],
"eligible":["형용사","be eligible for a discount","Members are eligible for a 10 percent discount.","회원은 10퍼센트 할인을 받을 자격이 있다."],
"enclose":["동사","please find enclosed","Please find enclosed a copy of your invoice.","송장 사본을 동봉하오니 확인해 주세요."],
"endorse":["동사","endorse a proposal","The board endorsed the proposal to open a new branch.","이사회는 새 지점을 여는 제안을 지지했다."],
"enroll":["동사","enroll in a course","Employees may enroll in the online course free of charge.","직원은 온라인 강좌에 무료로 등록할 수 있다."],
"estimate":["명사","a cost estimate","The contractor sent us a cost estimate for the repairs.","시공업자가 수리 비용 견적을 보내왔다."],
"exceed":["동사","exceed expectations","Third-quarter sales exceeded expectations.","3분기 매출이 기대를 넘어섰다."],
"expedite":["동사","expedite the process","We paid an extra fee to expedite the shipping process.","배송 처리를 앞당기려고 추가 요금을 냈다."],
"expire":["동사","expire at the end of the month","Your subscription will expire at the end of the month.","구독이 이번 달 말에 만료된다."],
"feasible":["형용사","economically feasible plan","The engineering team concluded that the proposed schedule is feasible.","엔지니어링 팀은 제안된 일정이 실현 가능하다고 결론 내렸다."],
"fluctuate":["동사","fluctuate widely","Fuel prices have fluctuated widely this year.","올해 연료 가격이 크게 변동했다."],
"forward":["동사","forward A to B","Could you forward the e-mail to the rest of the team?","그 이메일을 나머지 팀원에게 전달해 줄 수 있나요?"],
"headquarters":["명사","corporate headquarters","The corporate headquarters will move to Boston next year.","본사는 내년에 보스턴으로 이전한다."],
"implement":["동사","implement a new policy","The company will implement a new travel policy in May.","회사는 5월에 새 출장 정책을 시행한다."],
"inquiry":["명사","an inquiry about","We received several inquiries about the job opening.","채용 공고에 대한 문의를 여러 건 받았다."],
"inspection":["명사","a safety inspection","The factory will close for a safety inspection on Friday.","공장은 금요일에 안전 점검으로 문을 닫는다."],
"inventory":["명사","take inventory","The store closes early on Sunday to take inventory.","매장은 재고 조사를 위해 일요일에 일찍 문을 닫는다."],
"invoice":["명사","an outstanding invoice","Please pay the outstanding invoice within 30 days.","미지불 송장을 30일 안에 결제해 주세요."],
"itinerary":["명사","a detailed itinerary","Your travel agent will e-mail you a detailed itinerary.","여행사 직원이 자세한 일정표를 이메일로 보낼 것이다."],
"launch":["동사","launch a new product","The company plans to launch its new tablet in March.","회사는 3월에 새 태블릿을 출시할 계획이다."],
"lease":["명사","sign a lease","We signed a five-year lease on the office space.","우리는 그 사무실 공간을 5년간 임대하는 계약을 맺었다."],
"merger":["명사","a merger between A and B","The merger between the two banks was approved last week.","두 은행의 합병이 지난주 승인되었다."],
"negotiate":["동사","negotiate a contract","Our lawyers are negotiating the contract with the supplier.","우리 변호사들이 공급업체와 계약을 협상하고 있다."],
"notify":["동사","notify A of B","Please notify the front desk of any changes to your reservation.","예약 변경 사항이 있으면 프런트에 알려 주세요."],
"obtain":["동사","obtain permission","Visitors must obtain permission before taking photographs.","방문객은 사진을 찍기 전에 허가를 받아야 한다."],
"occupancy":["명사","occupancy rate","The hotel's occupancy rate rose to 92 percent in July.","7월에 호텔 객실 점유율이 92퍼센트로 올랐다."],
"outstanding":["형용사","an outstanding balance","Please settle your outstanding balance by Friday.","금요일까지 미지불 잔액을 정산해 주세요."],
"oversee":["동사","oversee the project","Ms. Patel will oversee the construction project.","파텔 씨가 그 건설 프로젝트를 감독한다."],
"patron":["명사","library patrons","Library patrons may borrow up to ten books at a time.","도서관 이용자는 한 번에 최대 10권까지 빌릴 수 있다."],
"payroll":["명사","on the payroll","The company has more than 300 people on the payroll.","그 회사의 급여 명단에는 300명이 넘는 직원이 있다."],
"periodically":["부사","be updated periodically","The price list is updated periodically.","가격표는 주기적으로 갱신된다."],
"personnel":["명사","personnel department","Submit the form to the personnel department.","그 양식을 인사부에 제출하세요."],
"postpone":["동사","postpone A until B","The launch has been postponed until next spring.","출시가 내년 봄으로 연기되었다."],
"preliminary":["형용사","preliminary results","Preliminary results show a rise in customer satisfaction.","예비 결과에 따르면 고객 만족도가 올랐다."],
"premises":["명사","on the premises","Smoking is not permitted anywhere on the premises.","구내 어디에서도 흡연할 수 없다."],
"prerequisite":["명사","a prerequisite for","A teaching certificate is a prerequisite for the position.","교원 자격증은 그 직책의 필수 조건이다."],
"promptly":["부사","promptly at 9 A.M.","The seminar will begin promptly at 9 A.M.","세미나는 오전 9시 정각에 시작한다."],
"proficient":["형용사","be proficient in","Applicants must be proficient in Spanish.","지원자는 스페인어에 능숙해야 한다."],
"projection":["명사","sales projections","Sales projections for next year are encouraging.","내년 매출 전망이 고무적이다."],
"promote":["동사","be promoted to","Mr. Lee was promoted to senior accountant.","이 씨는 선임 회계사로 승진했다."],
"proximity":["명사","in close proximity to","The hotel is in close proximity to the airport.","그 호텔은 공항과 아주 가깝다."],
"qualified":["형용사","be qualified for","She is highly qualified for the role.","그녀는 그 역할에 매우 적합한 자격을 갖췄다."],
"quote":["명사","get a quote","We got a quote from three moving companies.","이사 업체 세 곳에서 견적을 받았다."],
"receipt":["명사","upon receipt of","Payment is due upon receipt of the invoice.","송장을 받는 즉시 대금을 지불해야 한다."],
"recipient":["명사","award recipient","This year's award recipient will give a short speech.","올해 수상자가 짧은 연설을 할 것이다."],
"refund":["명사","a full refund","Customers can receive a full refund within 30 days.","고객은 30일 안에 전액 환불받을 수 있다."],
"reimburse":["동사","reimburse A for B","The company will reimburse you for travel expenses.","회사가 출장비를 상환해 줄 것이다."],
"relocate":["동사","relocate to","The design team will relocate to the fifth floor.","디자인 팀은 5층으로 이전한다."],
"renovation":["명사","under renovation","The east wing is currently under renovation.","동관은 현재 보수 공사 중이다."],
"representative":["명사","a sales representative","A sales representative will call you within 24 hours.","영업 담당자가 24시간 안에 전화를 드릴 것이다."],
"requirement":["명사","meet the requirements","Applicants who meet the requirements will be contacted.","요건을 충족하는 지원자에게 연락이 갈 것이다."],
"reservation":["명사","make a reservation","I'd like to make a reservation for four people.","네 명 예약하고 싶습니다."],
"retail":["명사","retail price","The retail price of the camera is $499.","그 카메라의 소매가는 499달러다."],
"revenue":["명사","generate revenue","Online sales generated most of the company's revenue.","온라인 판매가 회사 수익의 대부분을 창출했다."],
"revise":["동사","a revised schedule","Please see the revised schedule attached.","첨부된 수정 일정표를 보세요."],
"routine":["형용사","routine maintenance","The elevator is closed for routine maintenance.","엘리베이터가 정기 점검으로 운행하지 않는다."],
"shipment":["명사","track a shipment","You can track your shipment on our Web site.","웹사이트에서 배송 현황을 추적할 수 있다."],
"specification":["명사","according to specifications","The parts were made according to the client's specifications.","부품은 고객의 사양에 따라 제작되었다."],
"subscription":["명사","renew a subscription","You can renew your subscription online.","구독은 온라인으로 갱신할 수 있다."],
"substantial":["형용사","a substantial increase","There has been a substantial increase in online orders.","온라인 주문이 상당히 늘었다."],
"supervisor":["명사","report to a supervisor","Report any accidents to your supervisor immediately.","사고는 즉시 관리자에게 보고하세요."],
"supplier":["명사","switch suppliers","The restaurant switched suppliers to cut costs.","식당은 비용을 줄이려고 공급업체를 바꿨다."],
"tentative":["형용사","a tentative schedule","Here is a tentative schedule for the conference.","콘퍼런스 잠정 일정표입니다."],
"transaction":["명사","complete a transaction","You will receive a receipt once the transaction is complete.","거래가 완료되면 영수증을 받게 된다."],
"transfer":["동사","be transferred to","Ms. Okafor was transferred to the Singapore office.","오카포 씨는 싱가포르 지사로 전근되었다."],
"unanimous":["형용사","a unanimous decision","The committee reached a unanimous decision.","위원회는 만장일치로 결정했다."],
"upcoming":["형용사","the upcoming conference","Registration for the upcoming conference closes on Friday.","다가오는 콘퍼런스 등록은 금요일에 마감된다."],
"valid":["형용사","valid for 30 days","This coupon is valid for 30 days from the date of issue.","이 쿠폰은 발행일로부터 30일간 유효하다."],
"vendor":["명사","an approved vendor","Supplies must be ordered from an approved vendor.","비품은 승인된 판매업체에서 주문해야 한다."],
"warranty":["명사","under warranty","The printer is still under warranty, so repairs are free.","프린터가 아직 보증 기간이라 수리가 무료다."],
"reimbursement":["명사","submit an expense reimbursement form","Employees must submit receipts to receive reimbursement for travel costs.","직원은 출장비를 환급받으려면 영수증을 제출해야 한다."],
"reluctant":["형용사","be reluctant to do","The board members were reluctant to approve the high-risk expansion plan.","이사들은 위험 부담이 큰 확장 계획을 승인하기를 주저했다."],
"mandatory":["형용사","mandatory training session","Attendance at the safety seminar is mandatory for all factory workers.","안전 세미나 참석은 모든 공장 근로자에게 의무다."]
});
Object.assign(VX,{
"waive":["동사","waive the fee","The bank agreed to waive the annual fee for new business customers.","은행은 신규 기업 고객의 연회비를 면제해 주기로 했다."],
"yield":["동사","yield results","The new marketing campaign yielded better results than expected.","새 마케팅 캠페인은 예상보다 좋은 결과를 냈다."],
"on hand":["형용사구","have ~ on hand","Please keep extra printer cartridges on hand during the busy season.","바쁜 시기에는 여분의 프린터 카트리지를 비치해 두세요."],
"in advance":["부사구","book in advance","Tickets for the factory tour must be booked at least a week in advance.","공장 견학 티켓은 최소 일주일 전에 예약해야 한다."],
"be responsible for":["동사구","be responsible for the budget","Ms. Kwon is responsible for the department's travel budget.","권 씨는 부서의 출장 예산을 책임지고 있다."],
"be subject to":["동사구","be subject to change","All prices listed in the catalog are subject to change without notice.","카탈로그에 기재된 모든 가격은 예고 없이 변경될 수 있다."],
"take place":["동사구","take place at the venue","The awards ceremony will take place in the main ballroom.","시상식은 대연회장에서 열릴 것이다."],
"fill out":["동사구","fill out a form","Visitors must fill out a registration form at the front desk.","방문객은 안내 데스크에서 등록 양식을 작성해야 한다."],
"drop by":["동사구","drop by the office","Feel free to drop by my office if you have any questions.","질문이 있으면 언제든 제 사무실에 들르세요."],
"out of stock":["형용사구","be temporarily out of stock","The wireless keyboard is temporarily out of stock.","그 무선 키보드는 일시 품절이다."],
"in charge of":["형용사구","be in charge of ~","Mr. Diaz is in charge of the new product launch.","디아즈 씨가 신제품 출시를 담당하고 있다."],
"set up":["동사구","set up equipment","The technicians will set up the projector before the seminar begins.","기술자들이 세미나 시작 전에 프로젝터를 설치할 것이다."],
"take effect":["동사구","take effect immediately","The new dress code will take effect on March 1.","새 복장 규정은 3월 1일부터 시행된다."],
"on behalf of":["전치사구","on behalf of the company","I am writing on behalf of the entire sales team.","영업팀 전체를 대표하여 이 글을 씁니다."],
"be eligible for":["동사구","be eligible for a discount","Employees with one year of service are eligible for paid leave.","1년 근속한 직원은 유급 휴가를 받을 자격이 있다."],
"accessible":["형용사","easily accessible by subway","The new office is easily accessible by public transportation.","새 사무실은 대중교통으로 쉽게 갈 수 있다."],
"accountant":["명사","a certified accountant","The firm hired a certified accountant to prepare its tax returns.","그 회사는 세금 신고서를 작성할 공인 회계사를 고용했다."],
"adequate":["형용사","adequate staffing","The store needs adequate staffing during the holiday season.","매장은 연휴 기간에 충분한 인력이 필요하다."],
"advocate":["동사","advocate for change","Several board members advocated for a four-day workweek.","여러 이사가 주 4일 근무제를 지지했다."],
"affordable":["형용사","affordable prices","The café is popular with students because of its affordable prices.","그 카페는 저렴한 가격 덕분에 학생들에게 인기가 있다."],
"alternative":["명사","an alternative to ~","Video conferencing is a cheaper alternative to business travel.","화상 회의는 출장보다 저렴한 대안이다."],
"annual":["형용사","the annual report","The annual report will be released at the end of March.","연례 보고서는 3월 말에 발표될 것이다."],
"apparel":["명사","athletic apparel","The company plans to expand its line of athletic apparel.","그 회사는 운동복 제품군을 확대할 계획이다."],
"appliance":["명사","kitchen appliances","All units come with new kitchen appliances.","모든 세대에 새 주방 가전이 갖춰져 있다."],
"appraisal":["명사","a performance appraisal","Managers will conduct performance appraisals in December.","관리자들은 12월에 업무 평가를 실시할 것이다."],
"assess":["동사","assess the damage","An inspector came to assess the damage caused by the storm.","폭풍으로 인한 피해를 평가하기 위해 조사관이 왔다."],
"assign":["동사","be assigned to a project","Ms. Ortega has been assigned to the Tokyo project.","오르테가 씨는 도쿄 프로젝트에 배정되었다."],
"attendance":["명사","attendance at the meeting","Attendance at the monthly safety meeting is required.","월례 안전 회의 참석은 필수다."],
"audit":["명사","an internal audit","The finance department is preparing for an internal audit.","재무팀은 내부 감사를 준비하고 있다."],
"bid":["명사","submit a bid","Three construction firms submitted bids for the bridge project.","건설사 세 곳이 다리 공사에 입찰서를 제출했다."],
"capacity":["명사","seating capacity","The auditorium has a seating capacity of 300.","그 강당의 좌석 수용 인원은 300명이다."],
"collaborate":["동사","collaborate with ~ on ...","Our designers collaborated with a local artist on the new packaging.","우리 디자이너들은 새 포장 디자인을 위해 지역 예술가와 협업했다."],
"commence":["동사","commence on + 날짜","Construction of the new terminal will commence in April.","새 터미널 공사는 4월에 시작될 것이다."],
"commute":["명사","a daily commute","Many employees say working from home saves them a long commute.","많은 직원이 재택근무 덕분에 긴 통근 시간을 아낀다고 말한다."],
"compensate":["동사","compensate A for B","The airline compensated passengers for the long delay.","항공사는 긴 지연에 대해 승객들에게 보상했다."],
"competent":["형용사","a competent manager","Mr. Ito is a highly competent project manager.","이토 씨는 매우 유능한 프로젝트 관리자다."],
"compile":["동사","compile a report","The assistant compiled a list of potential suppliers.","비서는 잠재 공급업체 목록을 정리했다."],
"component":["명사","electronic components","The factory imports most of its electronic components from Taiwan.","그 공장은 전자 부품 대부분을 대만에서 수입한다."],
"comprehensive":["형용사","a comprehensive review","The consultant conducted a comprehensive review of our hiring process.","컨설턴트는 우리 채용 절차를 종합적으로 검토했다."],
"conduct":["동사","conduct a survey","The marketing team will conduct a customer survey next month.","마케팅팀은 다음 달에 고객 설문 조사를 실시할 것이다."]
});
Object.assign(VX,{
"consolidate":["동사","consolidate operations","The company plans to consolidate its two warehouses into one.","그 회사는 창고 두 곳을 하나로 통합할 계획이다."],
"consult":["동사","consult a specialist","Please consult the user manual before calling technical support.","기술 지원팀에 전화하기 전에 사용 설명서를 참고하세요."],
"correspondence":["명사","business correspondence","All correspondence should be addressed to the main office.","모든 서신은 본사 앞으로 보내야 한다."],
"credential":["명사","professional credentials","Applicants must submit copies of their professional credentials.","지원자는 전문 자격 증명서 사본을 제출해야 한다."],
"dealership":["명사","a car dealership","The car dealership is holding a sales event this weekend.","그 자동차 대리점은 이번 주말에 할인 행사를 연다."],
"decline":["명사","a decline in sales","The report shows a slight decline in sales this quarter.","보고서에 따르면 이번 분기 매출이 소폭 감소했다."],
"designate":["동사","a designated area","Smoking is allowed only in designated areas.","흡연은 지정된 구역에서만 허용된다."],
"dimension":["명사","the dimensions of","Please check the dimensions of the box before shipping.","발송 전에 상자 치수를 확인하세요."],
"discontinue":["동사","discontinue a product","The manufacturer will discontinue the older model in June.","제조사는 6월에 구형 모델 생산을 중단할 것이다."],
"dispatch":["동사","dispatch an order","Orders placed before noon are dispatched the same day.","정오 전 주문은 당일 발송된다."],
"diverse":["형용사","a diverse range of","The store offers a diverse range of kitchen products.","그 매장은 다양한 주방용품을 판매한다."],
"enhance":["동사","enhance customer service","The new software will enhance our customer service.","새 소프트웨어는 고객 서비스를 향상시킬 것이다."],
"ensure":["동사","ensure that","Please ensure that all doors are locked before leaving.","나가기 전에 모든 문이 잠겼는지 확인하세요."],
"entitle":["동사","be entitled to","Members are entitled to free parking.","회원은 무료 주차 혜택을 받을 자격이 있다."],
"evaluate":["동사","evaluate performance","Managers evaluate employee performance twice a year.","관리자들은 1년에 두 번 직원 성과를 평가한다."],
"exclusive":["형용사","an exclusive offer","Subscribers receive exclusive offers by e-mail.","구독자는 이메일로 독점 혜택을 받는다."],
"facilitate":["동사","facilitate communication","The new app facilitates communication between departments.","새 앱은 부서 간 소통을 원활하게 한다."],
"fare":["명사","a round-trip fare","The round-trip fare to Busan is 80,000 won.","부산 왕복 요금은 8만 원이다."],
"fragile":["형용사","fragile items","Fragile items must be packed with extra padding.","깨지기 쉬운 물건은 완충재를 더 넣어 포장해야 한다."],
"franchise":["명사","a franchise owner","The coffee chain is looking for new franchise owners.","그 커피 체인은 새 가맹점주를 찾고 있다."],
"fulfill":["동사","fulfill an order","We can fulfill most orders within two business days.","대부분의 주문은 영업일 이틀 안에 처리할 수 있다."],
"generate":["동사","generate revenue","The new product line generated $2 million in revenue.","새 제품군은 200만 달러의 수익을 창출했다."],
"grant":["명사","a research grant","The lab received a government research grant.","그 연구소는 정부 연구 보조금을 받았다."],
"incentive":["명사","offer an incentive","The company offers incentives to employees who meet their targets.","회사는 목표를 달성한 직원에게 장려금을 준다."],
"incur":["동사","incur expenses","Employees will be reimbursed for expenses incurred during business trips.","직원은 출장 중 발생한 비용을 환급받는다."],
"ingredient":["명사","fresh ingredients","The restaurant uses only fresh, local ingredients.","그 식당은 신선한 지역 식재료만 쓴다."],
"intensive":["형용사","an intensive course","She completed an intensive two-week language course.","그녀는 2주 집중 어학 과정을 마쳤다."],
"lodging":["명사","food and lodging","The conference fee includes food and lodging.","회의 참가비에는 식사와 숙박이 포함된다."],
"manufacture":["동사","be manufactured in","These parts are manufactured in our Daegu plant.","이 부품들은 대구 공장에서 제조된다."],
"modify":["동사","modify a design","The engineers modified the design to reduce costs.","엔지니어들은 비용을 줄이려고 설계를 수정했다."],
"nominate":["동사","be nominated for","Ms. Park was nominated for the employee of the year award.","박 씨는 올해의 직원상 후보에 올랐다."],
"outline":["동사","outline a plan","The director outlined the plan for next year.","이사가 내년 계획의 개요를 설명했다."],
"overdue":["형용사","an overdue payment","Please settle the overdue payment as soon as possible.","연체된 금액을 가능한 한 빨리 정산해 주세요."],
"pending":["형용사","pending approval","The project is pending approval from the board.","그 프로젝트는 이사회 승인을 기다리는 중이다."],
"perishable":["형용사","perishable goods","Perishable goods must be stored in the refrigerator.","상하기 쉬운 식품은 냉장고에 보관해야 한다."],
"precaution":["명사","take precautions","Workers must take safety precautions when using the machine.","작업자는 기계를 사용할 때 안전 예방 조치를 해야 한다."],
"procedure":["명사","follow the procedure","Please follow the standard procedure for returns.","반품 시 표준 절차를 따라 주세요."],
"procurement":["명사","procurement department","All purchases must be approved by the procurement department.","모든 구매는 조달 부서의 승인을 받아야 한다."],
"productivity":["명사","increase productivity","The new equipment has greatly increased productivity.","새 장비 덕분에 생산성이 크게 높아졌다."],
"prospective":["형용사","prospective clients","We will hold a tour for prospective clients next week.","다음 주에 잠재 고객을 위한 견학을 연다."]
});
Object.assign(VX,{
"quarterly":["형용사","quarterly earnings","The company will announce its quarterly earnings on Friday.","회사는 금요일에 분기 실적을 발표한다."],
"reasonable":["형용사","at a reasonable price","The hotel offers clean rooms at a reasonable price.","그 호텔은 깨끗한 객실을 합리적인 가격에 제공한다."],
"reception":["명사","a welcome reception","A welcome reception will be held in the lobby at 6 P.M.","오후 6시에 로비에서 환영회가 열린다."],
"redeem":["동사","redeem a voucher","Customers can redeem the voucher at any of our stores.","고객은 어느 매장에서든 상품권을 사용할 수 있다."],
"reference":["명사","a letter of reference","Please include two letters of reference with your application.","지원서에 추천서 두 통을 함께 제출하세요."],
"registration":["명사","online registration","Online registration for the workshop closes on May 1.","워크숍 온라인 등록은 5월 1일에 마감된다."],
"reliable":["형용사","a reliable supplier","We have worked with the same reliable supplier for ten years.","우리는 10년 동안 같은 믿을 만한 공급업체와 거래해 왔다."],
"remainder":["명사","the remainder of the year","The office will be closed for the remainder of the week.","사무실은 이번 주 남은 기간 동안 문을 닫는다."],
"remit":["동사","remit payment","Please remit payment within 30 days of receiving the invoice.","송장을 받은 지 30일 안에 대금을 송금해 주세요."],
"sanitation":["명사","sanitation standards","All restaurants must meet the city's sanitation standards.","모든 식당은 시의 위생 기준을 충족해야 한다."],
"scrutinize":["동사","scrutinize the figures","The auditors scrutinized the company's financial records.","감사인들은 회사의 재무 기록을 면밀히 조사했다."],
"stationery":["명사","office stationery","Office stationery is kept in the supply room.","사무용 문구류는 비품실에 보관되어 있다."],
"streamline":["동사","streamline the process","The new software will streamline the ordering process.","새 소프트웨어는 주문 절차를 간소화할 것이다."],
"surplus":["명사","a budget surplus","The city reported a budget surplus this year.","시는 올해 예산 흑자를 발표했다."],
"tenant":["명사","a new tenant","The new tenant will move in on the first of the month.","새 세입자는 다음 달 1일에 입주한다."],
"turnover":["명사","staff turnover","The company has reduced staff turnover with better benefits.","회사는 복지를 개선해 직원 이직률을 낮췄다."],
"utility":["명사","utility bills","Rent includes all utility bills except the Internet.","월세에는 인터넷을 제외한 모든 공과금이 포함된다."],
"voucher":["명사","a meal voucher","Passengers on delayed flights will receive a meal voucher.","지연된 항공편 승객은 식사권을 받는다."],
"adjourn":["동사","adjourn the meeting","The chair adjourned the meeting at 5 P.M.","의장은 오후 5시에 회의를 휴회했다."],
"abundant":["형용사","abundant natural resources","The region is known for its abundant natural resources.","그 지역은 풍부한 천연자원으로 유명하다."],
"accelerate":["동사","accelerate growth","The new investment will accelerate the company's growth.","새 투자는 회사의 성장을 가속할 것이다."],
"acclaim":["명사","critical acclaim","Her first novel received critical acclaim.","그녀의 첫 소설은 평단의 찬사를 받았다."],
"accompany":["동사","be accompanied by","Children under 12 must be accompanied by an adult.","12세 미만 어린이는 성인과 동반해야 한다."],
"accumulate":["동사","accumulate points","Members accumulate points with every purchase.","회원은 구매할 때마다 포인트를 쌓는다."],
"accurately":["부사","accurately reflect","The report accurately reflects this year's sales.","그 보고서는 올해 매출을 정확하게 반영한다."],
"acknowledge":["동사","acknowledge receipt of","Please acknowledge receipt of this e-mail.","이 이메일을 받았다고 확인해 주세요."],
"acquisition":["명사","the acquisition of","The acquisition of the software company was completed in May.","그 소프트웨어 회사 인수는 5월에 완료되었다."],
"adhere to":["동사구","adhere to the rules","All staff must adhere to the safety rules.","모든 직원은 안전 규칙을 준수해야 한다."],
"adjust":["동사","adjust the schedule","We adjusted the schedule to fit the client's needs.","우리는 고객의 요구에 맞게 일정을 조정했다."],
"administer":["동사","administer a test","The exam will be administered in Room 204.","시험은 204호에서 시행된다."],
"admission":["명사","free admission","Admission to the museum is free on Sundays.","일요일에는 박물관 입장이 무료다."],
"advance":["형용사","advance notice","Please give us at least two days' advance notice.","최소 이틀 전에 미리 알려 주세요."],
"affiliate":["명사","an overseas affiliate","The firm has affiliates in five countries.","그 회사는 5개국에 계열사가 있다."],
"aggressive":["형용사","an aggressive marketing campaign","The company launched an aggressive marketing campaign.","회사는 공격적인 마케팅 캠페인을 시작했다."],
"allowance":["명사","a travel allowance","Employees receive a monthly travel allowance.","직원은 매달 교통 수당을 받는다."],
"amend":["동사","amend a contract","Both parties agreed to amend the contract.","양측은 계약을 수정하기로 합의했다."],
"ample":["형용사","ample parking","The new store has ample parking for customers.","새 매장에는 고객용 주차 공간이 충분하다."],
"analyze":["동사","analyze data","The team spent a week analyzing the survey data.","팀은 설문 데이터를 분석하는 데 일주일을 썼다."],
"anonymous":["형용사","an anonymous survey","Employees can share feedback through an anonymous survey.","직원은 익명 설문으로 의견을 낼 수 있다."],
"apparent":["형용사","for no apparent reason","The printer stopped working for no apparent reason.","프린터가 뚜렷한 이유 없이 작동을 멈췄다."]
});
Object.assign(VX,{
"applaud":["동사","applaud the effort","The manager applauded the team's effort on the project.","매니저는 그 프로젝트에 대한 팀의 노력을 칭찬했다."],
"appreciate":["동사","appreciate your patience","We appreciate your patience during the renovation.","보수 공사 기간 동안 기다려 주셔서 감사합니다."],
"apprentice":["명사","an apprentice electrician","She worked as an apprentice electrician for two years.","그녀는 2년 동안 견습 전기 기사로 일했다."],
"approve":["동사","approve a request","The director approved the request for extra staff.","이사는 추가 인력 요청을 승인했다."],
"arrangement":["명사","make arrangements","Please make arrangements for the visitors' transportation.","방문객 교통편을 준비해 주세요."],
"articulate":["동사","articulate a vision","The CEO clearly articulated her vision for the company.","CEO는 회사에 대한 비전을 명확하게 밝혔다."],
"aspect":["명사","every aspect of","The consultant reviewed every aspect of our operations.","컨설턴트는 우리 운영의 모든 측면을 검토했다."],
"assemble":["동사","assemble furniture","The desks must be assembled before Monday.","책상들은 월요일 전에 조립되어야 한다."],
"assert":["동사","assert that","The report asserts that demand will continue to grow.","보고서는 수요가 계속 늘 것이라고 주장한다."],
"asset":["명사","a valuable asset","Ms. Park's language skills are a valuable asset to the team.","박 씨의 어학 능력은 팀에 귀중한 자산이다."],
"assume":["동사","assume responsibility for","Mr. Lee will assume responsibility for the Asian market.","이 씨가 아시아 시장에 대한 책임을 맡을 것이다."],
"assure":["동사","assure A that","We assure our customers that their data is safe.","저희는 고객 정보가 안전하다고 보장합니다."],
"attain":["동사","attain a goal","The team attained its sales goal two months early.","팀은 판매 목표를 두 달 일찍 달성했다."],
"attribute":["동사","attribute A to B","The company attributes its success to its loyal customers.","회사는 성공을 충성 고객 덕분으로 본다."],
"authentic":["형용사","authentic cuisine","The restaurant serves authentic Italian cuisine.","그 식당은 정통 이탈리아 요리를 낸다."],
"automate":["동사","automate a process","The new software automates the billing process.","새 소프트웨어는 청구 절차를 자동화한다."],
"backlog":["명사","clear a backlog","Extra staff were hired to clear the backlog of orders.","밀린 주문을 처리하려고 추가 인력을 고용했다."],
"balance":["명사","an outstanding balance","Please pay the outstanding balance by the end of the month.","미결제 잔액을 월말까지 납부해 주세요."],
"beneficial":["형용사","be beneficial to","Regular breaks are beneficial to employees' health.","규칙적인 휴식은 직원 건강에 유익하다."],
"benefit":["명사","employee benefits","The company offers generous employee benefits.","그 회사는 넉넉한 직원 복리후생을 제공한다."],
"boost":["동사","boost sales","The holiday promotion boosted sales by 20 percent.","연휴 판촉 행사로 매출이 20퍼센트 늘었다."],
"breakthrough":["명사","a major breakthrough","The lab made a major breakthrough in battery design.","그 연구소는 배터리 설계에서 큰 돌파구를 마련했다."],
"brief":["형용사","a brief meeting","We'll have a brief meeting before lunch.","점심 전에 짧은 회의를 하겠습니다."],
"broaden":["동사","broaden one's skills","The training program helps employees broaden their skills.","그 교육 프로그램은 직원들이 역량을 넓히도록 돕는다."],
"bulk":["명사","buy in bulk","Buying supplies in bulk saves the company money.","비품을 대량으로 사면 회사 비용이 절약된다."],
"cancellation":["명사","a cancellation fee","A cancellation fee applies to bookings canceled within 24 hours.","24시간 이내 취소에는 취소 수수료가 부과된다."],
"candid":["형용사","candid feedback","We welcome candid feedback from our customers.","고객의 솔직한 의견을 환영합니다."],
"capability":["명사","production capability","The new factory will double our production capability.","새 공장은 생산 능력을 두 배로 늘릴 것이다."],
"cater":["동사","cater an event","A local restaurant will cater the awards dinner.","지역 식당이 시상식 만찬에 음식을 제공할 것이다."],
"caution":["명사","use caution","Please use caution when handling chemicals.","화학 물질을 다룰 때는 주의하세요."],
"certify":["동사","be certified as","All of our technicians are certified by the manufacturer.","저희 기술자 모두 제조사의 인증을 받았습니다."],
"circulate":["동사","circulate a memo","The HR department circulated a memo about the new policy.","인사부는 새 정책에 관한 메모를 회람시켰다."],
"clarify":["동사","clarify a point","Could you clarify the last point in your report?","보고서의 마지막 요점을 명확히 설명해 주시겠어요?"],
"clearance":["명사","a clearance sale","The store is holding a clearance sale this weekend.","그 매장은 이번 주말에 재고 정리 세일을 한다."],
"commemorate":["동사","commemorate an anniversary","The firm held a dinner to commemorate its 50th anniversary.","회사는 창립 50주년을 기념해 만찬을 열었다."],
"commend":["동사","commend A for B","The mayor commended the volunteers for their hard work.","시장은 자원봉사자들의 노고를 칭찬했다."],
"commission":["명사","earn a commission","Sales staff earn a commission on every sale.","판매 직원은 판매할 때마다 수수료를 받는다."],
"commitment":["명사","a commitment to quality","Our commitment to quality has never changed.","품질에 대한 우리의 약속은 한 번도 변한 적이 없다."],
"compatible":["형용사","be compatible with","This charger is compatible with most phones.","이 충전기는 대부분의 휴대폰과 호환된다."],
"competitive":["형용사","a competitive salary","We offer a competitive salary and flexible hours.","저희는 경쟁력 있는 급여와 유연 근무를 제공합니다."]
});

Object.assign(VX,{
"complement":["동사","complement each other","The two designs complement each other well.","두 디자인은 서로 잘 보완한다."],
"comply":["동사","comply with regulations","All vendors must comply with safety regulations.","모든 판매업체는 안전 규정을 준수해야 한다."],
"concise":["형용사","a concise summary","Please keep your report short and concise.","보고서는 짧고 간결하게 작성해 주세요."],
"conclude":["동사","conclude a meeting","The meeting concluded with a short Q&A session.","회의는 짧은 질의응답으로 마무리되었다."],
"confirm":["동사","confirm a reservation","Please confirm your reservation by Friday.","금요일까지 예약을 확정해 주세요."],
"conform":["동사","conform to standards","All products must conform to industry standards.","모든 제품은 업계 표준에 맞아야 한다."],
"consecutively":["부사","for three years consecutively","The firm has won the award three years consecutively.","그 회사는 3년 연속으로 그 상을 받았다."],
"consensus":["명사","reach a consensus","The board reached a consensus on the budget.","이사회는 예산에 대해 합의에 이르렀다."],
"considerable":["형용사","a considerable amount","The project required a considerable amount of time.","그 프로젝트에는 상당한 시간이 들었다."],
"constraint":["명사","budget constraints","Due to budget constraints, the event was scaled down.","예산 제약 때문에 행사 규모가 줄었다."],
"consumption":["명사","energy consumption","The new system reduces energy consumption by 20%.","새 시스템은 에너지 소비를 20% 줄인다."],
"contingency":["명사","a contingency plan","We need a contingency plan in case of bad weather.","악천후에 대비한 비상 계획이 필요하다."],
"contribute":["동사","contribute to success","Every team member contributed to the project's success.","모든 팀원이 프로젝트 성공에 기여했다."],
"convene":["동사","convene a meeting","The committee will convene next Monday.","위원회는 다음 주 월요일에 소집된다."],
"conventional":["형용사","conventional methods","The new process is faster than conventional methods.","새 공정은 기존 방식보다 빠르다."],
"convert":["동사","convert A into B","The old warehouse was converted into offices.","낡은 창고가 사무실로 개조되었다."],
"convey":["동사","convey a message","The ad clearly conveys the brand's message.","그 광고는 브랜드 메시지를 분명히 전달한다."],
"cooperate":["동사","cooperate with","The two firms cooperated with each other on the project.","두 회사는 그 프로젝트에서 서로 협력했다."],
"courteous":["형용사","courteous staff","Our courteous staff are happy to help.","저희 친절한 직원들이 기꺼이 도와드립니다."],
"coverage":["명사","insurance coverage","The policy provides full coverage for water damage.","그 보험은 누수 피해를 전액 보장한다."],
"criteria":["명사","selection criteria","Applicants must meet all the selection criteria.","지원자는 모든 선발 기준을 충족해야 한다."],
"crucial":["형용사","play a crucial role","Customer feedback plays a crucial role in our planning.","고객 의견은 우리 계획에서 중대한 역할을 한다."],
"cuisine":["명사","local cuisine","The restaurant is famous for its local cuisine.","그 식당은 향토 요리로 유명하다."],
"customize":["동사","customize a product","Customers can customize their orders online.","고객은 온라인에서 주문을 맞춤 설정할 수 있다."],
"decade":["명사","over the past decade","Sales have doubled over the past decade.","지난 10년간 매출이 두 배로 늘었다."],
"dedicate":["동사","be dedicated to","The company is dedicated to customer satisfaction.","그 회사는 고객 만족에 전념한다."],
"deduct":["동사","deduct A from B","Taxes are deducted from your monthly salary.","세금은 월급에서 공제된다."],
"defer":["동사","defer payment","Customers may defer payment for up to 60 days.","고객은 최대 60일까지 결제를 미룰 수 있다."],
"deficit":["명사","a budget deficit","The city is facing a large budget deficit.","시는 큰 예산 적자에 직면해 있다."],
"delegation":["명사","a trade delegation","A trade delegation from Japan visited the factory.","일본 무역 대표단이 공장을 방문했다."],
"deliberately":["부사","deliberately designed","The lobby was deliberately designed to feel open.","로비는 개방감이 들도록 의도적으로 설계되었다."],
"demonstrate":["동사","demonstrate a product","The sales rep demonstrated how the device works.","영업 담당자가 기기 작동법을 시연했다."],
"densely":["부사","densely populated","The store is located in a densely populated area.","그 매장은 인구 밀도가 높은 지역에 있다."],
"depart":["동사","depart from","The train departs from Platform 3 at 9:00.","열차는 9시에 3번 승강장에서 출발한다."],
"dependable":["형용사","a dependable supplier","We need a dependable supplier for raw materials.","원자재를 위한 믿을 만한 공급업체가 필요하다."],
"deplete":["동사","deplete supplies","Heavy demand quickly depleted our supplies.","수요가 몰려 재고가 빠르게 바닥났다."],
"deteriorate":["동사","deteriorate rapidly","Road conditions deteriorated rapidly in the storm.","폭풍 속에서 도로 상태가 급격히 악화되었다."],
"devise":["동사","devise a plan","The team devised a plan to cut costs.","팀은 비용 절감 계획을 고안했다."],
"diagnose":["동사","diagnose a problem","The technician quickly diagnosed the problem.","기술자가 문제를 빠르게 진단했다."],
"disclose":["동사","disclose information","The firm did not disclose the price of the deal.","회사는 거래 가격을 공개하지 않았다."]
});
