/* card extras for the word list: VX[word]=[품사, 짝꿍 표현, 예문, 예문 해석]. Add more with Object.assign(VX,{...}). */
Object.assign(VX,{
"accommodate":["동사","accommodate the growing demand","The newly built hotel can accommodate over 400 guests comfortably.","새로 지은 호텔은 400명 이상의 투숙객을 편안하게 수용할 수 있다."],
"acquire":["동사","acquire a competitor","Harlow Foods plans to acquire a smaller rival by the end of the year.","할로우 푸드는 연말까지 더 작은 경쟁사를 인수할 계획이다."],
"adjacent":["형용사","adjacent to the lobby","The meeting room adjacent to the lobby has been reserved for the interviews.","로비 옆 회의실이 면접용으로 예약되었다."],
"agenda":["명사","the first item on the agenda","The budget review is the first item on the agenda.","예산 검토가 안건의 첫 번째 항목이다."],
"allocate":["동사","allocate funds for","The city allocated additional funds for road repairs.","시는 도로 보수에 추가 자금을 배정했다."],
"amenity":["명사","hotel amenities","Guests can enjoy amenities such as a pool and a fitness center.","투숙객은 수영장과 피트니스 센터 같은 편의시설을 이용할 수 있다."],
"anticipate":["동사","anticipate an increase in","We anticipate an increase in sales during the holiday season.","우리는 연휴 기간에 매출이 늘 것으로 예상한다."],
"applicant":["명사","qualified applicants","Only qualified applicants will be contacted for an interview.","자격을 갖춘 지원자에게만 면접 연락을 드립니다."],
"appoint":["동사","be appointed (as) director","Ms. Ruiz was appointed as the new marketing director.","루이즈 씨가 새 마케팅 이사로 임명되었다."],
"approximately":["부사","approximately 30 minutes","The tour lasts approximately 30 minutes.","투어는 약 30분 걸린다."],
"attire":["명사","business attire","Business attire is required at the awards dinner.","시상식 만찬에는 비즈니스 정장이 필요하다."],
"authorize":["동사","authorize a payment","Only the finance manager can authorize payments over $5,000.","5천 달러가 넘는 지급은 재무 관리자만 승인할 수 있다."],
"available":["형용사","be available for","Mr. Chen is not available for a meeting until Thursday.","첸 씨는 목요일까지 회의할 시간이 없다."],
"beverage":["명사","food and beverages","Food and beverages are not permitted in the library.","도서관 안에는 음식과 음료를 반입할 수 없다."],
"brochure":["명사","a product brochure","Please take a product brochure on your way out.","나가실 때 제품 안내 책자를 가져가세요."],
"budget":["명사","within budget","The renovation was completed on time and within budget.","보수 공사는 제시간에 예산 안에서 끝났다."],
"candidate":["명사","a candidate for the position","Three candidates for the position will be interviewed on Monday.","그 직책의 후보자 세 명이 월요일에 면접을 본다."],
"comply with":["동사구","comply with safety regulations","All visitors must comply with the plant's safety regulations.","모든 방문객은 공장의 안전 규정을 준수해야 한다."],
"complimentary":["형용사","complimentary breakfast","All rooms include a complimentary breakfast.","모든 객실에 무료 조식이 포함된다."],
"confidential":["형용사","strictly confidential document","All personnel records must be kept in a strictly confidential file.","모든 인사 기록은 엄격한 기밀 문서함에 보관해야 한다."],
"consecutive":["형용사","for the third consecutive year","The company posted record profits for the third consecutive year.","그 회사는 3년 연속 사상 최대 이익을 냈다."],
"contract":["명사","sign a contract","Both parties signed the contract on Friday.","양측은 금요일에 계약서에 서명했다."],
"coordinate":["동사","coordinate with","Please coordinate with the IT team before installing new software.","새 소프트웨어를 설치하기 전에 IT 팀과 조율하세요."],
"courier":["명사","by courier","The signed documents were sent by courier this morning.","서명된 서류는 오늘 아침 택배로 발송되었다."],
"defective":["형용사","defective merchandise","Defective merchandise may be returned for a full refund.","결함 있는 상품은 반품하고 전액 환불받을 수 있다."],
"delegate":["동사","delegate tasks to","Good managers delegate routine tasks to their staff.","좋은 관리자는 일상 업무를 직원에게 위임한다."],
"deadline":["명사","meet the deadline","The team worked overtime to meet the deadline.","팀은 마감일을 맞추려고 초과 근무를 했다."],
"dedicated":["형용사","be dedicated to","The firm is dedicated to providing excellent service.","그 회사는 훌륭한 서비스를 제공하는 데 전념한다."],
"deposit":["명사","a security deposit","A security deposit of one month's rent is required.","한 달 치 임대료의 보증금이 필요하다."],
"distribute":["동사","distribute handouts to","The speaker distributed handouts to all participants.","발표자는 모든 참가자에게 유인물을 나눠 주었다."],
"durable":["형용사","durable materials","The backpacks are made from durable, waterproof materials.","그 배낭은 튼튼한 방수 소재로 만들어졌다."],
"eligible":["형용사","be eligible for a discount","Members are eligible for a 10 percent discount.","회원은 10퍼센트 할인을 받을 자격이 있다."],
"enclose":["동사","please find enclosed","Please find enclosed a copy of your invoice.","송장 사본을 동봉하오니 확인해 주세요."],
"endorse":["동사","endorse a proposal","The board endorsed the proposal to open a new branch.","이사회는 새 지점을 여는 제안을 지지했다."],
"enroll":["동사","enroll in a course","Employees may enroll in the online course free of charge.","직원은 온라인 강좌에 무료로 등록할 수 있다."],
"estimate":["명사","a cost estimate","The contractor sent us a cost estimate for the repairs.","시공업자가 수리 비용 견적을 보내왔다."],
"exceed":["동사","exceed expectations","Third-quarter sales exceeded expectations.","3분기 매출이 기대를 넘어섰다."],
"expedite":["동사","expedite the process","We paid an extra fee to expedite the shipping process.","배송 처리를 앞당기려고 추가 요금을 냈다."],
"expire":["동사","expire at the end of the month","Your subscription will expire at the end of the month.","구독이 이번 달 말에 만료된다."],
"feasible":["형용사","economically feasible plan","The engineering team concluded that the proposed schedule is feasible.","엔지니어링 팀은 제안된 일정이 실현 가능하다고 결론 내렸다."],
"fluctuate":["동사","fluctuate widely","Fuel prices have fluctuated widely this year.","올해 연료 가격이 크게 변동했다."],
"forward":["동사","forward A to B","Could you forward the e-mail to the rest of the team?","그 이메일을 나머지 팀원에게 전달해 줄 수 있나요?"],
"headquarters":["명사","corporate headquarters","The corporate headquarters will move to Boston next year.","본사는 내년에 보스턴으로 이전한다."],
"implement":["동사","implement a new policy","The company will implement a new travel policy in May.","회사는 5월에 새 출장 정책을 시행한다."],
"inquiry":["명사","an inquiry about","We received several inquiries about the job opening.","채용 공고에 대한 문의를 여러 건 받았다."],
"inspection":["명사","a safety inspection","The factory will close for a safety inspection on Friday.","공장은 금요일에 안전 점검으로 문을 닫는다."],
"inventory":["명사","take inventory","The store closes early on Sunday to take inventory.","매장은 재고 조사를 위해 일요일에 일찍 문을 닫는다."],
"invoice":["명사","an outstanding invoice","Please pay the outstanding invoice within 30 days.","미지불 송장을 30일 안에 결제해 주세요."],
"itinerary":["명사","a detailed itinerary","Your travel agent will e-mail you a detailed itinerary.","여행사 직원이 자세한 일정표를 이메일로 보낼 것이다."],
"launch":["동사","launch a new product","The company plans to launch its new tablet in March.","회사는 3월에 새 태블릿을 출시할 계획이다."],
"lease":["명사","sign a lease","We signed a five-year lease on the office space.","우리는 그 사무실 공간을 5년간 임대하는 계약을 맺었다."],
"merger":["명사","a merger between A and B","The merger between the two banks was approved last week.","두 은행의 합병이 지난주 승인되었다."],
"negotiate":["동사","negotiate a contract","Our lawyers are negotiating the contract with the supplier.","우리 변호사들이 공급업체와 계약을 협상하고 있다."],
"notify":["동사","notify A of B","Please notify the front desk of any changes to your reservation.","예약 변경 사항이 있으면 프런트에 알려 주세요."],
"obtain":["동사","obtain permission","Visitors must obtain permission before taking photographs.","방문객은 사진을 찍기 전에 허가를 받아야 한다."],
"occupancy":["명사","occupancy rate","The hotel's occupancy rate rose to 92 percent in July.","7월에 호텔 객실 점유율이 92퍼센트로 올랐다."],
"outstanding":["형용사","an outstanding balance","Please settle your outstanding balance by Friday.","금요일까지 미지불 잔액을 정산해 주세요."],
"oversee":["동사","oversee the project","Ms. Patel will oversee the construction project.","파텔 씨가 그 건설 프로젝트를 감독한다."],
"patron":["명사","library patrons","Library patrons may borrow up to ten books at a time.","도서관 이용자는 한 번에 최대 10권까지 빌릴 수 있다."],
"payroll":["명사","on the payroll","The company has more than 300 people on the payroll.","그 회사의 급여 명단에는 300명이 넘는 직원이 있다."],
"periodically":["부사","be updated periodically","The price list is updated periodically.","가격표는 주기적으로 갱신된다."],
"personnel":["명사","personnel department","Submit the form to the personnel department.","그 양식을 인사부에 제출하세요."],
"postpone":["동사","postpone A until B","The launch has been postponed until next spring.","출시가 내년 봄으로 연기되었다."],
"preliminary":["형용사","preliminary results","Preliminary results show a rise in customer satisfaction.","예비 결과에 따르면 고객 만족도가 올랐다."],
"premises":["명사","on the premises","Smoking is not permitted anywhere on the premises.","구내 어디에서도 흡연할 수 없다."],
"prerequisite":["명사","a prerequisite for","A teaching certificate is a prerequisite for the position.","교원 자격증은 그 직책의 필수 조건이다."],
"promptly":["부사","promptly at 9 A.M.","The seminar will begin promptly at 9 A.M.","세미나는 오전 9시 정각에 시작한다."],
"proficient":["형용사","be proficient in","Applicants must be proficient in Spanish.","지원자는 스페인어에 능숙해야 한다."],
"projection":["명사","sales projections","Sales projections for next year are encouraging.","내년 매출 전망이 고무적이다."],
"promote":["동사","be promoted to","Mr. Lee was promoted to senior accountant.","이 씨는 선임 회계사로 승진했다."],
"proximity":["명사","in close proximity to","The hotel is in close proximity to the airport.","그 호텔은 공항과 아주 가깝다."],
"qualified":["형용사","be qualified for","She is highly qualified for the role.","그녀는 그 역할에 매우 적합한 자격을 갖췄다."],
"quote":["명사","get a quote","We got a quote from three moving companies.","이사 업체 세 곳에서 견적을 받았다."],
"receipt":["명사","upon receipt of","Payment is due upon receipt of the invoice.","송장을 받는 즉시 대금을 지불해야 한다."],
"recipient":["명사","award recipient","This year's award recipient will give a short speech.","올해 수상자가 짧은 연설을 할 것이다."],
"refund":["명사","a full refund","Customers can receive a full refund within 30 days.","고객은 30일 안에 전액 환불받을 수 있다."],
"reimburse":["동사","reimburse A for B","The company will reimburse you for travel expenses.","회사가 출장비를 상환해 줄 것이다."],
"relocate":["동사","relocate to","The design team will relocate to the fifth floor.","디자인 팀은 5층으로 이전한다."],
"renovation":["명사","under renovation","The east wing is currently under renovation.","동관은 현재 보수 공사 중이다."],
"representative":["명사","a sales representative","A sales representative will call you within 24 hours.","영업 담당자가 24시간 안에 전화를 드릴 것이다."],
"requirement":["명사","meet the requirements","Applicants who meet the requirements will be contacted.","요건을 충족하는 지원자에게 연락이 갈 것이다."],
"reservation":["명사","make a reservation","I'd like to make a reservation for four people.","네 명 예약하고 싶습니다."],
"retail":["명사","retail price","The retail price of the camera is $499.","그 카메라의 소매가는 499달러다."],
"revenue":["명사","generate revenue","Online sales generated most of the company's revenue.","온라인 판매가 회사 수익의 대부분을 창출했다."],
"revise":["동사","a revised schedule","Please see the revised schedule attached.","첨부된 수정 일정표를 보세요."],
"routine":["형용사","routine maintenance","The elevator is closed for routine maintenance.","엘리베이터가 정기 점검으로 운행하지 않는다."],
"shipment":["명사","track a shipment","You can track your shipment on our Web site.","웹사이트에서 배송 현황을 추적할 수 있다."],
"specification":["명사","according to specifications","The parts were made according to the client's specifications.","부품은 고객의 사양에 따라 제작되었다."],
"subscription":["명사","renew a subscription","You can renew your subscription online.","구독은 온라인으로 갱신할 수 있다."],
"substantial":["형용사","a substantial increase","There has been a substantial increase in online orders.","온라인 주문이 상당히 늘었다."],
"supervisor":["명사","report to a supervisor","Report any accidents to your supervisor immediately.","사고는 즉시 관리자에게 보고하세요."],
"supplier":["명사","switch suppliers","The restaurant switched suppliers to cut costs.","식당은 비용을 줄이려고 공급업체를 바꿨다."],
"tentative":["형용사","a tentative schedule","Here is a tentative schedule for the conference.","콘퍼런스 잠정 일정표입니다."],
"transaction":["명사","complete a transaction","You will receive a receipt once the transaction is complete.","거래가 완료되면 영수증을 받게 된다."],
"transfer":["동사","be transferred to","Ms. Okafor was transferred to the Singapore office.","오카포 씨는 싱가포르 지사로 전근되었다."],
"unanimous":["형용사","a unanimous decision","The committee reached a unanimous decision.","위원회는 만장일치로 결정했다."],
"upcoming":["형용사","the upcoming conference","Registration for the upcoming conference closes on Friday.","다가오는 콘퍼런스 등록은 금요일에 마감된다."],
"valid":["형용사","valid for 30 days","This coupon is valid for 30 days from the date of issue.","이 쿠폰은 발행일로부터 30일간 유효하다."],
"vendor":["명사","an approved vendor","Supplies must be ordered from an approved vendor.","비품은 승인된 판매업체에서 주문해야 한다."],
"warranty":["명사","under warranty","The printer is still under warranty, so repairs are free.","프린터가 아직 보증 기간이라 수리가 무료다."],
"reimbursement":["명사","submit an expense reimbursement form","Employees must submit receipts to receive reimbursement for travel costs.","직원은 출장비를 환급받으려면 영수증을 제출해야 한다."],
"reluctant":["형용사","be reluctant to do","The board members were reluctant to approve the high-risk expansion plan.","이사들은 위험 부담이 큰 확장 계획을 승인하기를 주저했다."],
"mandatory":["형용사","mandatory training session","Attendance at the safety seminar is mandatory for all factory workers.","안전 세미나 참석은 모든 공장 근로자에게 의무다."]
});
